openshift/source-to-image

cmd/sti/main.go
=> Added forcePull flag to usage command

cmd/sti/main.go, pkg/sti/create.go, pkg/sti/create/templates/docker.go, pkg/sti/create/templates/scripts.go, pkg/sti/create/templates/test.go
This is an attempt to provide a generator for new STI images. As an author of a new STI image, I don't want to spend time creating and copying content to STI scripts / etc but I want to have a boilerplate I can start work with.
```
mkdir new-image
sti create openshift/new-image ./new_image
```
This will create `.sti` folder with sample STI scripts, Dockerfile, `test/run` script and Makefile.
=> Added STI image generator

pkg/sti/executor.go, pkg/sti/executor_test.go
This is a followup PR to #106.
@mfojtik review pls?
=> Moving the code responsible for setting up the workingDir structure into one place

cmd/sti/main.go, pkg/sti/build.go, pkg/sti/script/installer.go
=> Fixed handling STI scripts which are placed just inside the sources and used with arbitrary image

hack/test-go.sh
Per https://github.com/openshift/origin/pull/699
=> Exclude .git from test search

README.md, docs/builder_image.md
=> Fixed typo in save-artifacts description

pkg/sti/docker/docker.go, pkg/sti/executor.go, pkg/sti/test/docker.go
https://bugzilla.redhat.com/show_bug.cgi?id=1185730
=> bug_1185730

Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/test/docker.go
This makes the detection based on the Image tag name obsolete.
=> Improve OnBuild detection by looking into Image metadata

cmd/sti/main.go, docs/cli.md, pkg/build/interfaces.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go, pkg/test/docker.go
This will be waiting for #129 to be merged first.
=> Card devexp_426 - Enable retrieving images for incremental builds from external repo.

pkg/api/scripts.go, pkg/api/types.go, pkg/build/interfaces.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/sti/usage.go, pkg/build/strategies/sti/usage_test.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/errors/errors.go, pkg/scripts/install.go, pkg/scripts/install_test.go, pkg/test/fs.go, pkg/test/install.go
Special dedication to @mfojtik :bouquet:
=> Changed Script -> string for readability

.travis.yml
=> Fixed test-go.sh variables KUBE -> STI

cmd/sti/main.go, docs/cli.md, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/config/config.go
=> Issue 146 - make output image optional

pkg/build/strategies/layered/layered.go, pkg/build/strategies/sti/sti.go
This addresses the problem described in #149.
=> Issue 149 - reading logs is done with bufio.NewReader instead of bufio.NewScanner

pkg/build/strategies/sti/sti_test.go, pkg/git/clone.go, pkg/git/clone_test.go, pkg/util/fs.go
=> Fixed copy operation upon working with local application source

cmd/sti/main.go, docs/cli.md
=> Card origin_devexp_538 - Updated docs with --quiet flag

pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go
@bparees this is initial take to fix the problem with custom `assemble` script inside source repo and `run` pointing to non existent file. This is not ready yet as I need to address  the tests.
=> Fixed script path when invoking PostExecute.

pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
@bparees @rhcarvalho this fix should solve your problems. Sorry for that  :disappointed:
[test]
=> Fixed the PostExecute command and added tests to cover that part

pkg/tar/tar.go
This is to address problem from #171.
@mfojtik @bparees PTAL
//fyi @Maxim-Filimonov
=> Issue 171 - fixed properly closing files upon untarring.

cmd/sti/main.go, docs/cli.md, pkg/create/templates/test.go, pkg/errors/errors.go
Fixes #187.
@bparees @mfojtik PTAL
=> Issue 187 - change parameters from camelCase to hyphen-names

pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
=> Do not attempt to pull incremental image when ForcePull is false during

cmd/sti/main.go, pkg/api/printer.go, pkg/api/types.go, pkg/util/env.go
=> Add support for --environment-file/-E

pkg/docker/docker.go, pkg/docker/docker_test.go, test/integration/images/sti-fake-env/Dockerfile, test/integration/images/sti-fake-no-tar/Dockerfile, test/integration/images/sti-fake-scripts-no-save-artifacts/Dockerfile, test/integration/images/sti-fake-scripts/Dockerfile, test/integration/images/sti-fake/Dockerfile
This PR mainly addresses #179, but it also contains removals mentioned in #199.
@bparees @csrwng PTAL
=> Issue179 - fix sti hangs when using non-existent latest

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/docker_test.go
This reverts commit c356fe5ad449b0f8ffd02d40afe3c54b0b7173ff.  https://github.com/openshift/source-to-image/pull/208
=> Revert "Allow passing DNS servers and search suffixes to build container"

cmd/sti/main.go, docs/builder_image.md, docs/cli.md, pkg/api/describe/describer.go, pkg/api/scripts.go, pkg/api/types.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/errors/errors.go, pkg/scripts/download.go, pkg/scripts/install.go, test/integration/images/sti-fake-scripts-no-save-artifacts/Dockerfile, test/integration/images/sti-fake-scripts/Dockerfile, test/integration/images/sti-fake/Dockerfile
Address #205.
@bparees @mfojtik PTAL
=> Issue 205 - renamed io.openshift.sti.* label to shorter io.s2i.*

docs/builder_image.md, docs/cli.md
This update is to match upstream changes https://github.com/openshift/openshift-docs/pull/433
@bparees PTAL
=> Moved sti scripts docs under builder section where it belongs more.

pkg/build/strategies/sti/sti_test.go, pkg/errors/errors.go, pkg/git/clone.go, pkg/git/clone_test.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1190106
(once it makes it to origin)
=> [DO_NOT_MERGE] report proper error for unrecognized source protocol

docs/builder_image.md
=> Updated documentation within builder_image.md

pkg/create/create.go, pkg/create/templates/docker.go, pkg/create/templates/scripts.go, pkg/create/templates/test.go
Update sti create command with:
- file permissions of created files
- contents of all created files
@mfojtik @bparees ptal
=> sti create fixes

docs/builder_image.md, pkg/create/templates/scripts.go, pkg/create/templates/test.go
=> Doc clarifications

cmd/sti/main.go, docs/cli.md
=> Rewording and fixing capitalizations

README.md
=> Rewording and updating README.md

pkg/create/templates/docker.go, pkg/create/templates/scripts.go, pkg/create/templates/test.go
=> Applied comments from @csrwng to create

pkg/create/templates/docker.go, pkg/create/templates/test.go
=> Additional changes to the create command, to produce valid builder image contents.

README.md
=> Adding URL to reference Docker docs re ONBUILD

pkg/build/config.go, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/test/docker.go
=> Added fallback to use local image when Builder's PullImage fails

docs/builder_image.md, pkg/create/templates/docker.go, pkg/docker/docker.go
=> Fixed some leftovers from moving to new label scheme including: docs,getDestination method and template for Dockerfile.

test/integration/integration_test.go
@bparees @soltysh I have a pull request for the changes needed to enable STI loggging when -v is passed into the test-integration.sh
=> issue 133 turn on loglevel 5 when -v passed into test script

pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/errors/errors.go
Displays an error when no-root condition is not met
=> Add error for no-root condition

hack/build-test-images.sh, hack/test-integration.sh, test/integration/images/sti-fake-onbuild/Dockerfile, test/integration/integration_test.go
@soltysh @bparees PTAL - *begins* to address issue #203
=> Adding test cases for ONBUILD strategy builds

.gitignore, README.md, docs/cli.md, docs/debugging-s2i.md
@bparees @soltysh @mfojtik Gentlemen, my introductory pass at the sti debug guide.  I'll incorporate comments from you all as best I can as I see them.
My intention is to close out issue 133 once this is good to merge upstream.
Fixed https://github.com/openshift/source-to-image/issues/133
=> issue133: introduce sti debug guide

pkg/create/templates/docker.go
following the same change in sti-base : https://github.com/openshift/sti-base/pull/58
=> Rename /opt/openshift to /opt/app-root

pkg/create/templates/test.go
A few fixes for the "test" script template : 
- support for running on OSX
- fix incremental build
- more logs
=> Some fixes for the test script template

pkg/util/labels.go
=> Get source context-dir from SourceInfo

cmd/sti/main.go, docs/cli.md, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/test/client.go, pkg/docker/util.go, pkg/run/run.go
@bparees @soltysh Gentlemen, the PR for issue 180.
Fixed https://github.com/openshift/source-to-image/issues/180
=> issue180: launch resulting image in container for diagnostic purposes

cmd/sti/main.go
@bparees I guess that's your leftover :wink:
=> Removed debug leftover

.travis.yml, hack/common.sh, hack/verify-gofmt.sh, hack/verify-golint.sh
=> Added support for go1.5

.travis.yml, Makefile, hack/common.sh, hack/install-tools.sh, hack/test-go.sh, hack/util.sh, hack/verify-govet.sh
@bparees this is post #276 I'm adding govet, though it'll not fail yet with errors, similarly to what we do with golint. I've also cleaned the `Makefile` a bit to follow origin patterns.
=> Adding govet

Godeps/Godeps.json, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/.travis.yml, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/AUTHORS, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/auth.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/auth_test.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/change.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container_test.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/exec.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/image.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/image_test.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/misc.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/server.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/server_test.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/volume.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/volume_test.go
Update go-dockerclient to match k8s and origin -> https://github.com/openshift/origin/pull/4535
=> bump(github.com/fsouza/go-dockerclient) 76fd6c68cf24c48ee6a2b25def997182a29f940e

pkg/git/git.go
This will show this:
```console
E0910 11:54:40.262701 16000 git.go:100] Clone failed: fatal: '/home/mfojtik/sandbox/sample-app/asdf' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
instead of:
```console
I0910 11:34:21.688327 01656 clone.go:35] Git clone failed: exit status 128
```
=> Show error message from GIT when the git clone operation fails

hack/test-integration.sh, hack/test-stirunimage.sh, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/test/docker.go
Merges existing image labels with other labels when committing image.
=> Fix integration test by merging labels of committed image

pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/scm/file/download.go, pkg/scm/scm.go, pkg/scm/scm_test.go
=> Fix various issues with using local directories with sources

pkg/tar/tar_test.go
=> pkg/tar/tar_test: remove temporary files after executing tests.

pkg/tar/tar.go
Clean the input dir when creating a tar (prevents path truncation when creating tar header) and avoid calling chmod when OS is windows (otherwise an error is thrown).
=> tar: avoid calling chmod when OS is windows and clean input dir

pkg/api/describe/describer.go, pkg/api/types.go, pkg/api/validation/validation.go, pkg/api/validation/validation_test.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go
Provides openshift origin with the ability to control the network settings of
sti containers.
=> Introduce NetworkMode option

pkg/api/types.go, pkg/build/strategies/sti/sti.go
realized that it does not make sense to keep this as nobody will ever use it... also cleaned up the messy 'if' in printer
=> Remove UseLogger

pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/scm.go, pkg/scm/scm_test.go, pkg/test/git.go
@bparees @csrwng from email exchange this weekend and @csrwng heads up on Friday.  Also added a quick verification for bugzilla 1268478
=> don't require .git suffix; consolidate validation, empty protocol URL processing

cmd/s2i/main.go
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>
=> typo: build -> built

pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/scm.go, pkg/scm/scm_test.go, pkg/test/git.go
This reverts commit 73dd2c2d0946e098a233f6ac56a4e2d91e22204d.
=> Revert "don't require .git suffix; consolidate URL validation and no protocol construction"

cmd/s2i/main.go, pkg/docker/docker.go, pkg/docker/fake_docker.go, pkg/docker/test/client.go, pkg/docker/util.go
=> Verify if we can connect to Docker daemon

cmd/s2i/main.go, hack/test-stirunimage.sh, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/scm.go, pkg/scm/scm_test.go, pkg/test/git.go
=> don't require .git suffix; consolidate validation, empty protocol URL processing (revisited)

pkg/build/strategies/sti/sti.go, pkg/test/callback.go, pkg/util/callback.go, pkg/util/callback_test.go
Fixes: https://github.com/openshift/source-to-image/issues/66
=> Add source info into callback

cmd/s2i/main.go, pkg/api/types.go, pkg/build/interfaces.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/sti/usage.go, pkg/build/strategies/sti/usage_test.go, pkg/docker/docker.go
Fixes: https://github.com/openshift/source-to-image/issues/81
This allows to execute the assemble script under specified user.
=> Add --assemble-user option

pkg/scm/git/clone.go, pkg/scm/git/clone_test.go, pkg/scm/git/git.go, pkg/test/git.go
Adds submodule update and init commands. See issue in origin:
https://github.com/openshift/origin/issues/5910
=> Add submodule commands

hack/common.sh
=> use --tags for git-describe

hack/test-stirunimage.sh, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go
Fixes: https://github.com/openshift/source-to-image/issues/81
=> Commit container with original builder user

pkg/tar/tar.go
Fixes: https://github.com/openshift/source-to-image/issues/358
=> Fix how we detect symlinks

cmd/s2i/main.go
Fixes: https://github.com/openshift/source-to-image/issues/357
=> Print S2I version when running in verbose mode

pkg/build/strategies/sti/sti.go
Related to: https://github.com/openshift/source-to-image/issues/81#issuecomment-157994022
=> Use assemble user to save artifacts

Makefile
Fixes #308.
@php-coder @mfojtik ptal
=> Fixed misleading example in Makefile

cmd/s2i/main.go
=> Fix file descriptor leak when .dockercfg was found

pkg/create/templates/scripts.go
small improvements related to the conversation [here](https://github.com/openshift/source-to-image/pull/371#discussion_r47234750)
=> updated scripts templates for s2i create

pkg/build/strategies/onbuild/onbuild.go, pkg/util/fs.go
Fixes: https://github.com/openshift/source-to-image/issues/363
As a bonus, this should also work on Windows is it does not rely on "cp" binary.
@csrwng @bparees PTAL
=> Fix copying the local directory

README.md, examples/README.md, examples/nginx-app/Dockerfile, examples/nginx-app/assemble, examples/nginx-app/run, examples/nginx-app/save-artifacts, examples/nginx-app/test/index.html, examples/nginx-app/usage
Minimal reference for s2i builder image.
this is related to https://trello.com/c/d6WQuBS4/537-3-add-minimal-reference-sti-image
=> Minimal s2i builder image tutorial

docs/cli.md
I have been approach several times with question: "why the s2i isn't building the latest changes in my repository?" and the answer usually was that "you need to commit all your changes", so I figured out it would be wise to have this info in our docs, i case anyone would read them :P
=> Update docs: local git changes have to be commited

pkg/api/describe/describer.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/fake_docker.go, pkg/util/injection.go, pkg/util/injection_test.go, test/integration/images/sti-fake/Dockerfile, test/integration/integration_test.go, test/integration/scripts/.sti/bin/assemble
* Truncate the rm-injections script itself
* Add describer
=> More things that we missed in the injections PR

pkg/scripts/install.go
=> Fix .sti/bin detection

pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go
@bparees @csrwng PTAL
this PR is for addressing the new flavor of bugzilla 1261117 (builder img with no tar), where we enter the layered path via `oc new-app` vs. `s2i`.
The build image name is getting set with the docker image ref / ending with @<hex img id>
=> handle builder image names ending in hex image ids

README.md
fixes https://github.com/openshift/source-to-image/issues/406
=> clarify root/docker group security

README.md, cmd/s2i/main.go, docs/builder_image.md, docs/cli.md, pkg/config/config.go, pkg/scripts/environment.go
Fixes leftovers from #275.
@mfojtik @bparees
=> S2i leftovers

cmd/s2i/main.go, pkg/api/describe/describer.go, pkg/api/types.go, pkg/cmd/util.go, pkg/docker/fake_docker.go
Fixes #412 supersedes #413.
@bparees ptal
=> expose previous image pull policy as a flag

pkg/build/strategies/sti/sti.go
=> Update log message to show correct image tag

hack/rebase-to-origin.sh
@mfojtik giving love to your script... ptal
@php-coder FYI :eyes:
=> :heart: give love

README.md
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Add badges for Go Report Card and License

cmd/s2i/main.go, docs/cli.md, pkg/api/types.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/scm/scm.go, pkg/scm/scm_test.go
Fixes https://github.com/openshift/source-to-image/issues/367
@bparees @mfojtik PTAL
=> add option to only attempt copy command on source url

pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/docker/fake_docker.go, pkg/docker/test/client.go
The objective is to fix concurrency issues with the current implementation.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1315607.
=> Rework RunContainer implementation

pkg/ignore/ignore_test.go
Dead code found, dead code killed...
Also "fixing" the import order.
@mfojtik @soltysh PTAL
=> Kill dead code

pkg/run/run.go
- Update doc comments to match Go's convention
https://golang.org/doc/effective_go.html
- Reorganize imports to match convention
- Call errors 'err', no need for prefixes
=> Refactor pkg/run

pkg/docker/docker.go, pkg/util/timeout.go, pkg/util/timeout_test.go
Follow up for https://github.com/openshift/source-to-image/pull/444
@bparees PTAL
=> Improve messaging for Docker timeouts

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/scripts/download.go, pkg/scripts/install.go, pkg/scripts/install_test.go
Allows specifying a proxy configuration for script download in the api.Config
=> Allow passing a proxy configuration for script download

pkg/docker/docker.go
=> Change imports to follow project standards

hack/build-test-images.sh, hack/test-integration.sh
Not really a love affair with Bash...
=> Improve Bash scripts

cmd/s2i/main.go
@mfojtik PTAL. Trying to make our life easier if we'll ever look at that TODO again...
=> Clarify TODO message

README.md, docs/builder_image.md
fixes https://github.com/openshift/source-to-image/issues/472
=> reference openshift image guidelines

pkg/build/strategies/sti/sti.go, pkg/docker/docker.go
Fixes: https://github.com/openshift/source-to-image/issues/475
=> Set entrypoint to /bin/env

pkg/build/strategies/sti/sti.go, pkg/docker/docker.go
This reverts commit 355822d5eab0d60e5e65112afb036d327b236c22.
=> Revert "Set entrypoint to /bin/env"

pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go
Rename `b` to more meaningful name `builder`.
PTAL @mfojtik @bparees
CC @PI-Victor
=> pkg/build/strategies: rename b to builder

cmd/s2i/main.go, pkg/api/describe/describer.go, pkg/build/cleanup.go, pkg/build/config.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/create/create.go, pkg/ignore/ignore.go, pkg/util/injection.go
I did a misc minor refactorings while I was reading the code. Probably, it could be incorporated to our code base. Each of the commits have meaningful description. If you don't want to accept some of them, I can remove any of them. After yours feedback I'll rebase them of course.
PTAL @mfojtik @bparees
=> Minor improvements

pkg/docker/docker.go
I've refactored `runContainerTar()` by extracting 3 methods from it and inlining original one.
Despite this is just refactoring it's a part of the logic for running the containers and it's important to have this code more readable and understandable. I believe that after my refactoring, the code became easy to read/modify (at least for me :-D).
PTAL @bparees @rhcarvalho 
CC @mfojtik
=> Refactor runContainerTar method

pkg/build/strategies/sti/sti.go
Extracts 6 methods from `PostExecute()` method to make it shorter, readable and easy to modify.
PTAL @bparees
=> Refactor PostExecute() method

pkg/build/strategies/sti/sti.go
Because [Golang doesn't provide method similar to `COALESCE()`](https://github.com/golang/go/issues/14423) I introduced our own.
I hope that no one will object about this.
PTAL @bparees @mfojtik @rhcarvalho
=> strategies/sti/sti.go: add firstNonEmpty() method

README.md
=> update readme w/ benefits/goals of s2i

pkg/tar/tar.go
=> tar(StreamDirAsTar,StreamFileAsTar): fix possible fd leak and handle error from Stat()

pkg/docker/docker.go, pkg/scm/git/clone.go, pkg/scripts/environment.go, pkg/scripts/install.go
Attempting to address concerns from openshift/origin#9247
=> Changing messaging to Clayton's spec

pkg/util/glog/glog.go
Addressing openshift/origin#9645
=> Fixing race condition in s2i's new glog replacement

pkg/util/fs.go
When running on windows, calls out to system to delete a directory to avoid golang issue https://github.com/golang/go/issues/9606
When we switch to golang 1.7, we can remove the workaround.
=> Fix directory delete in Windows

pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/run/run.go
fixes https://github.com/openshift/source-to-image/issues/549
@php-coder ptal
=> move DefaultEntrypoint constant to sti package

pkg/build/strategies/sti/postexecutorstep.go
=> Fix path to assemble-runtime script when it's inside of the runtime image

pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, test/integration/images/sti-fake-env/Dockerfile, test/integration/images/sti-fake-no-tar/Dockerfile, test/integration/images/sti-fake-scripts-no-save-artifacts/Dockerfile, test/integration/images/sti-fake-scripts/Dockerfile, test/integration/images/sti-fake/Dockerfile
@grahamdumpleton ptal. 
fixes https://github.com/openshift/source-to-image/issues/559
[test]
=> Change override entrypoint to /usr/bin/env

pkg/errors/errors.go, pkg/scm/scm.go
=> Removed unused MissingGitRepositoryError

pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/docker/util.go, pkg/run/run.go
=> Fixing line number accuracy with glog wrapper

pkg/build/strategies/sti/sti.go, pkg/scripts/environment.go, pkg/scripts/environment_test.go
PTAL @bparees 
Let me know if you think that I also should rename `EnvironmentSpec` to `Environment`.
Fixes #545
=> Fix Environment and EnvironmentSpec duplication

README.md, docs/user_guide.md
PTAL @bparees 
https://trello.com/c/FJ7ZVLhR/1016-3-document-and-investigate-s2i-exit-hooks
=> Document how to invoke embedded scripts from custom scripts

pkg/docker/docker.go
Bug 1368074
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1368074
Detailed explanation
A timing window existed, seen first with incremental builds and the new engine-api/k8s docker client, where the attach container would never return because of a blocking channel call
@bparees PTAL
=> s2i: intermittent hang

docs/user_guide.md
Backport of fixes to https://github.com/openshift/openshift-docs/pull/2697 and https://github.com/openshift/openshift-docs/pull/2724
PTAL @bparees
=> docs/user_guide.md: backport minor fixes from OpenShift documentation

pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/run/run.go
@php-coder and @gabemontero ptal.  this is a follow up to the ongoing issues described in:
https://github.com/openshift/source-to-image/issues/475#issuecomment-238088669
=> only override entrypoint in image if one is set

pkg/build/strategies/sti/sti.go
@bparees PTAL
stems from recent discussion in https://github.com/openshift/origin/pull/10776
=> better defer waitgroup Done pattern

.travis.yml, pkg/test/git.go, pkg/test/tar.go
=> bump go versions used by travis

pkg/api/types.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/util/status/build_status.go, pkg/util/status/doc.go
@bparees in order to avoid duplication and a really weird long switch statement in OpenShift, i attached the detail messages for the failure reason to s2i, (where they actually belong after all).
PTAL.
=> add failure message

pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/test/git.go
=> teach isValidGitRepository about git submodules

Godeps/Godeps.json, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/docker/util.go, vendor/github.com/openshift/origin/LICENSE, vendor/github.com/openshift/origin/pkg/image/reference/reference.go, vendor/github.com/openshift/origin/pkg/image/reference/reference_test.go
Dependent on #607 which should be good to go.
Fixes #614.
=> Use github.com/openshift/origin/pkg/image/reference

pkg/create/templates/test.go
When using docker machine on Mac tests can't access container ip directly, so I'm using docker machine ip.
The host port could be change, so we get it from container.
=> Fix container_ip function on Mac

docs/cli.md, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/postexecutorstep_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/util/callback.go, test/integration/integration_test.go
=> Invoke callback URL when build has failed

pkg/api/types.go, pkg/build/config.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/util/status/build_status.go
add additional failure reasons and also small refactoring
[test]
=> Improve failure reasons

pkg/docker/util.go
fixes https://github.com/openshift/source-to-image/issues/640
@jim-minter ptal
=> handle empty docker auths cleanly

Godeps/Godeps.json, vendor/github.com/Microsoft/go-winio/README.md, vendor/github.com/Microsoft/go-winio/backup.go, vendor/github.com/Microsoft/go-winio/file.go, vendor/github.com/Microsoft/go-winio/fileinfo.go, vendor/github.com/Microsoft/go-winio/pipe.go, vendor/github.com/Microsoft/go-winio/privilege.go, vendor/github.com/Microsoft/go-winio/sd.go, vendor/github.com/Microsoft/go-winio/syscall.go, vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
The minor fixes contained finally get us to a point where we can run things like `go build ./...` or `go test ./...` in the repo, which is nice!
=> bump github.com/Microsoft/go-winio

Godeps/Godeps.json, vendor/golang.org/x/sys/windows/asm.s, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/golang.org/x/sys/windows/env_unset.go, vendor/golang.org/x/sys/windows/mksyscall.go, vendor/golang.org/x/sys/windows/syscall.go, vendor/golang.org/x/sys/windows/syscall_windows.go, vendor/golang.org/x/sys/windows/zsyscall_windows.go, vendor/golang.org/x/sys/windows/ztypes_windows.go
As well as being a required change, I am using this PR to test the CI system; please don't merge...
=> bump(golang.org/x/sys/windows) 8d1157a435470616f975ff9bb013bea8d0962067

Godeps/Godeps.json, Makefile, hack/verify-godeps.sh, tools/godepchecker/godepchecker.go, vendor/github.com/spf13/pflag/.travis.yml, vendor/github.com/spf13/pflag/bool.go, vendor/github.com/spf13/pflag/count.go, vendor/github.com/spf13/pflag/flag.go, vendor/github.com/spf13/pflag/float32.go, vendor/github.com/spf13/pflag/float64.go, vendor/github.com/spf13/pflag/int.go, vendor/github.com/spf13/pflag/int32.go, vendor/github.com/spf13/pflag/int64.go, vendor/github.com/spf13/pflag/int8.go, vendor/github.com/spf13/pflag/string.go, vendor/github.com/spf13/pflag/string_array.go, vendor/github.com/spf13/pflag/string_slice.go, vendor/github.com/spf13/pflag/uint.go, vendor/github.com/spf13/pflag/uint16.go, vendor/github.com/spf13/pflag/uint32.go, vendor/github.com/spf13/pflag/uint64.go, vendor/github.com/spf13/pflag/uint8.go
Added a checker to ensure s2i's godeps match origin's.  Currently, warnings are printed but do not cause make verify to bomb out.
Bumped two vendorings to match origin as well.
@soltysh
=> Godepchecker

docs/builder_image.md
fixes https://github.com/openshift/source-to-image/issues/650
=> clarify the output of save-artifacts cannot include anything except the tar stream

pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/util/status/build_status.go
also other formatting options for newfailure reason
[test]
=> make status messages compliant with origin

cmd/s2i/main.go, pkg/errors/errors.go
Signed-off-by: yuanxiao <yuan.xiao5@zte.com.cn>
=> refactor func checkErr to CheckError

cmd/s2i/main.go, contrib/completions/bash/s2i, contrib/completions/zsh/s2i, hack/update-generated-completions.sh, hack/verify-bash-completion.sh, pkg/errors/errors.go
fixes https://github.com/openshift/source-to-image/issues/665
=> add zsh completions for s2i command

README.md
Closes: #668
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Update required Go version in README

pkg/build/strategies/sti/sti.go
already check the err value,decided return nil end the New() func
=> decided return nil end the New() func

Godeps/Godeps.json, vendor/github.com/golang/glog/README, vendor/github.com/golang/glog/glog.go
after this and https://github.com/openshift/origin/pull/12089, openshift and s2i godeps will actually match eachother.
=> bump(github.com/golang/glog) 44145f04b68cf362d9c4df2182967c2275eaefed

pkg/scripts/download.go
=> modify log format

pkg/util/injection.go
=> modify log info

pkg/docker/docker.go
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1391665
=> use indefinite timeout for docker commit

README.md
=> fixing broken link in README.md

cmd/s2i/main.go
fix https://github.com/openshift/source-to-image/issues/701
=> fix Default s2i rebuild image pull policy not work correctly

README.md
Updating sample s2i build command to use a repo that is currently working correctly.
Also updated sample docker run command to map the port correctly
Fixes #700
=> Updating sample commands

pkg/build/strategies/sti/sti.go
=> updating support for dash shell

pkg/build/strategies/sti/sti.go
fixes https://github.com/openshift/source-to-image/issues/705
=> ensure defer file removal is run

pkg/api/helpers.go, pkg/api/types.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/strategies.go, pkg/util/status/build_status.go, pkg/util/status/build_status_test.go
Gathers build step timing information for significant build steps and records it, making it available to the 'oc describe' command
Dependency for https://github.com/openshift/origin/pull/13307
=> Gather build step timing information

Makefile
fix these:
1. make test invalid
2. example pkg/build no test files
=> fix invalid test session

pkg/docker/docker.go
=> Add retry action for pulling builder image

pkg/docker/docker.go, pkg/util/env.go, pkg/util/env_test.go
needed for bug https://bugzilla.redhat.com/show_bug.cgi?id=1366795
=> strip proxy credentials from proxy variables before logging them

pkg/create/templates/docker.go, pkg/create/templates/test.go
@bparees found this while working on my app for PyCon, ptal
=> Fix test template to match created directories

cmd/s2i/main.go, pkg/api/describe/describer.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/sti/usage.go, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/docker/fake_docker.go, pkg/docker/util.go, pkg/run/run.go, pkg/scripts/download.go, test/integration/dockerssl_test.go, test/integration/integration_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1442875
@openshift/devex
@bparees ptal - running this against origin tests + extended tests at https://github.com/openshift/origin/pull/13817 then intend to repurpose that PR for the s2i vendoring bump.
=> Always close pipes in RunContainer(), in order to avoid hang in error cases

pkg/docker/docker.go
=> silence failed to kill container warning

examples/nginx-centos7/Dockerfile
=> fixes chown error in example Dockerfile

hack/build-release.sh, hack/common.sh
=> strip debug symbols on release binary

pkg/build/strategies/sti/sti.go
Backport of openshift/source-to-image#743 for 1.5
=> Pull image before executing S2I script [1.5]

pkg/build/strategies/sti/sti.go
Backport of openshift/source-to-image#743 for 1.4
=> Pull image before executing S2I script [1.4]

pkg/ignore/ignore.go, pkg/ignore/ignore_test.go
Updating pkg/ignore/ignore.go to skip blank lines in the .s2iignore file
Added test to pkg/ignore/ignore_test.go to test for blank line issues
Fixes #752
=> Skip blank lines in .s2iignore file

docs/new_labels.md, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, test/integration/integration_test.go, test/integration/scripts/.s2i/bin/assemble
Checks if a JSON file with labels exist. If so, update and/or add the labels before the output images is committed.
=> Update and/or add docker labels with a JSON file

README.md
=> Documentation: Installation using go get

pkg/config/config.go
Restoring multiple environment variables from an .s2ifile
does not work correctly since removing the ability to supply
a comma separated list of environment variables on the cli.
This pull request restores the environment variables back into
a list before running the command when building the command from
a saved .s2ifile
Fixes #761
=> .s2ifile restore multiple environment variables not working

pkg/tar/tar.go, pkg/tar/tar_test.go
=> include directories in tar files

hack/test-stirunimage.sh, pkg/build/strategies/sti/sti.go, pkg/test/fs.go, pkg/util/fs.go, test_apprepo/.s2i/bin/assemble, test_apprepo/.s2i/bin/run
bug 1467819
https://bugzilla.redhat.com/show_bug.cgi?id=1467819
=> ensure created directories are readable/executable

docs/cli.md, pkg/util/callback.go, pkg/util/callback_test.go, test/integration/integration_test.go
=> Removing Payload field

pkg/scm/git/clone_test.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go
fixes https://github.com/openshift/source-to-image/issues/766
=> make git quiet unless verbose logging is enabled

hack/rebase-to-origin.sh
didn't realise this script existed, but since it does...
=> git describe tags in rebase-to-origin.sh

hack/windows/Vagrantfile
=> Parse $USER and set VM name accordingly

examples/nginx-centos7/Dockerfile, examples/nginx-centos7/README.md, examples/nginx-centos7/s2i/bin/assemble, examples/nginx-centos7/test/test-app-redirect/nginx.conf
Since me and my team have been using the s2i functionality to configure services in the containers, I think it'd be great to have an example of this in the main repo, so that others could benefit from seeing this approach. Please let me know what you think!
=> Make it possible to configure example nginx server

pkg/test/fs/fs.go, pkg/util/fs/fs.go, pkg/util/fs/fs_test.go
associated with bugzilla 1506173
=> implement functionality to copy symlinks and not their contents

pkg/cmd/cli/cmd/build.go, pkg/scm/git/url.go
fixes https://github.com/openshift/source-to-image/issues/847
=> error out on unparseable urls

vendor/github.com/docker/docker/client/hijack.go
https://github.com/moby/moby/issues/36516
https://github.com/moby/moby/pull/36517
=> UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function

tools/depchecker/godepchecker.go
=> Fix comment in godepchecker

hack/test-stirunimage.sh, pkg/api/types.go, pkg/api/types_test.go, test/integration/integration_test.go
=> Parse multiple volumes via semicolon delimeter.

pkg/util/env.go, pkg/util/env_test.go
Addresses issue brought up in BZ 1571349
=> Improve URL redaction

docs/cli.md
fixes https://github.com/openshift/source-to-image/issues/893
=> fix image repository name

pkg/api/constants/doc.go, pkg/api/constants/env.go, pkg/api/constants/labels.go, pkg/api/constants/scripts.go, pkg/api/types.go, pkg/build/config.go, pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/sti/usage.go, pkg/build/strategies/sti/usage_test.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/errors/errors.go, pkg/ignore/ignore.go, pkg/ignore/ignore_test.go, pkg/scm/downloaders/file/download.go, pkg/scm/downloaders/git/clone.go, pkg/scripts/environment.go, pkg/scripts/install.go, pkg/scripts/install_test.go, pkg/util/labels.go
Moved docker labels and s2i scripts constants to separate top-level package.
Fixes #882
=> Constants package

pkg/build/strategies/dockerfile/dockerfile.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1598013
=> enforce current dir as default working dir

pkg/cmd/cli/cmd/build.go
fixes https://github.com/openshift/source-to-image/issues/904
=> clarify git clone behavior

pkg/build/strategies/dockerfile/dockerfile.go, pkg/scm/downloaders/file/download.go, pkg/scm/downloaders/file/download_test.go
fixes https://github.com/openshift/source-to-image/issues/903
=> disallow copies to target into the source dir of the copy

pkg/build/strategies/dockerfile/dockerfile.go, pkg/errors/errors.go, pkg/scm/downloaders/file/download.go
=> Remove references to cli flags in errors

examples/nginx-centos7/s2i/bin/assemble, examples/nginx-centos7/s2i/bin/save-artifacts, pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/cmd/cli/cmd/build.go, pkg/util/strings.go, test/integration/integration_test.go
Incremental Dockerfile Build
Allow incremental `--as-dockerfile` builds.
Trello card: https://trello.com/c/P6TZg0wO/1582-5-builds-s2i-incremental-build-as-dockerfile
=> Incremental Dockerfile Build

.gitignore
@openshift/sig-developer-experience ptal
=> update gitignore for vscode, vscode debug, metadata

pkg/build/strategies/dockerfile/dockerfile.go, test/integration/integration_test.go
Ensure all chown commands run as root.
Assemble user in general does not have permission to do this.
=> Dockerfile Run COPY and CHOWN as root

docs/builder_image.md, docs/user_guide.md
=> URL of OKD is docs.okd.io now

hack/install-tools.sh, pkg/tar/tar.go
fixes https://github.com/openshift/source-to-image/issues/929
=> increase timeout on tar extraction and make error clearer

pkg/build/strategies/sti/sti.go
=> Clean up the artifacts directory on untar error

pkg/scm/downloaders/file/download.go
Adds the possibility to ignore files/folder before copying content.
Fixes #937 
/cc @bparees 
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
=> Fix recursive copy when using --as-dockerfile on non scm-managed folder

pkg/tar/tar.go, pkg/tar/tar_test.go
* Allow tar streams readers to set their own timeouts
* Use PAX format to support UTF-8 filenames consistently
=> Support UTF-8 Filenames in tar streaming

AUTHORS
=> Add Adam Kaplan as author

hack/build-release.sh, images/release/Dockerfile
- Use podman instead of docker
- Use UBI as base image
- Bump golang
=> Fixes to release process

README.md
Docker Images -> contianer images
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Make s2i less Docker centric

pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/ignore/ignore.go, pkg/scm/downloaders/file/download.go, pkg/scm/downloaders/git/clone.go, pkg/test/fs/fs.go, pkg/util/fs/fs.go, pkg/util/fs/fs_test.go, test/integration/integration_test.go
=> Apply .s2iignore during copy from local directory

hack/build-release.sh, images/release/Dockerfile
* Fixes recent change to podman cp
=> Bump release golang to 1.12.5

.gitignore, pkg/api/constants/scripts.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/util/labels.go, pkg/util/labels_test.go
/assign @adambkaplan 
@bparees @otaviof @sbose78 @openshift/openshift-team-developer-experience  FYI
=> Bug 1758305: support .s2i/image_metadata.json with --as-dockerfile

.dockerignore, Dockerfile
Building project to run as a container image.
=> Container Image

README.md
=> update example to use newer ruby image

hack/build-release.sh
Fix release script to allow an override build command.
Works with `podman` or `docker`.
=> Allow releases with podman or docker

pkg/cmd/cli/cli.go, pkg/cmd/cli/cmd/build.go, pkg/cmd/cli/cmd/generate.go, pkg/cmd/cli/util/util.go, pkg/config/config.go, pkg/docker/docker_test.go, pkg/docker/util_test.go, pkg/tar/tar.go, pkg/util/fs/fs.go, test/generate_test.go, test/integration/docker/integration_test.go
=> Cleaning up imports

.travis.yml, hack/common.sh
Add ppc64le support for ci job on travis-ci.
=> Add ppc64le support

Dockerfile, hack/common.sh
=> Fix multi-arch builds

pkg/create/templates/readme.go
=> Fix instruction in s2i create README template

hack/test-stirunimage.sh, pkg/api/types.go, pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/dockerfile/dockerfile_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/cmd/cli/cmd/build.go, pkg/cmd/cli/cmd/generate.go, pkg/scripts/install.go, pkg/scripts/install_test.go, pkg/util/labels.go
see https://github.com/shipwright-io/build/issues/810
=> update script url from builder image labels with s2i build --as-dockerfile

pkg/cmd/cli/cmd/generate.go
=> S2I command always uses 'latest' tag

.tekton/source-to-image-pull-request.yaml, .tekton/source-to-image-push.yaml, Dockerfile
Changes:
- Add ppc64le and s390x to the multi-build pipeline
=> Add ppc64le and s390x architecture

.tekton/source-to-image-pull-request.yaml, .tekton/source-to-image-push.yaml
Changes:
- Re-apply changes after Konflux workspace update to ocp-tools-s2
=> Reapply changes after Konflux workspace update

go.mod, go.sum, vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/oc/errors.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go, vendor/github.com/containerd/errdefs/pkg/LICENSE, vendor/github.com/containerd/errdefs/pkg/errgrpc/grpc.go, vendor/github.com/containerd/errdefs/pkg/internal/cause/cause.go, vendor/github.com/containerd/errdefs/pkg/internal/types/collapsible.go, vendor/modules.txt
- errdefs package location was changed and that caused panic while
building for windows
- update Microsoft/hcsshim to 0.12.9 that includes the fix for errdefs
- fixes #1204
Signed-off-by: Avinal Kumar <avinal@redhat.com>
=> fix: update Microsoft/hcsshim to fix build on Windows
