pkg/sti/executor.go
and handle errors from shell commands.
Note that this doesn't address the regular output of shell commands, which still need to be integrated into the logging framework.
=> fix #106 build with source from local file system

cmd/sti/main.go, pkg/sti/config/config.go
This saves you from typing all parameters for `sti build` command. It stores them when you run the command for the first time and then you can just run `sti build` (without arguments).
It stores the options into `.stifile` (and attempts to read then from this location).
This also enable us to ship the `.stifile` in application GIT repositories, so if you want to build the application image, you don't need to search for the STI builder image name.
UPDATE:
You have to enable this behavior by using the `--use-config` flag.
=> Store the STI build command line to disk

pkg/sti/build.go, pkg/sti/build_test.go, pkg/sti/errors/errors.go, pkg/sti/executor.go
@csrwng could you please have a look, since I'm modifying the expected error behavior slightly, I wanted to get rid of the hack that @smarterclayton didn't like, in favor of passing the error output (which is limited to 1024) up the stack.
=> Bug 1182464 - added info from failing container

pkg/sti/config/config.go
Initialize Flags alongside the rest initialization of Config so that the
underlying map reference will point to an initialized map and not nil
which can cause runtime panics if someone tries to write to it in between
the Config initialization and the [current](https://github.com/openshift/source-to-image/blob/9fad846d68808d43a815072db4d075cbe5012c05/pkg/sti/config/config.go#L32) map initialization
(blog.golang.org/go-maps-in-action)
=> Initialize Flags on the spot

cmd/sti/main.go, docs/cli.md, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, test/integration/integration_test.go
After talking to @mfojtik we've decided to rename the `Clean` variable to `Incremental` to better match current behavior. This came up when doing https://github.com/openshift/origin/pull/1101.
/cc @bparees
=> Card devexp_426 - Renaming Clean to Incremental to better match current behaviour, where Incremental needs to be forced

README.md, docs/cli.md
This is a part of work on https://trello.com/c/UJG1mPZf/364-3-v3-ruby-image-image-beta2
Also last step before we cant get rid of the ruby-20-centos repository
=> Renaming ruby-20-centos to new ruby-20-centos7

hack/common.sh, pkg/version/version.go
Fixed some leftovers in the release process, especially the binary version which was trying to modify old package `pkg/sti/version` instead of `pkg/version`.
@bparees PTAL
=> Bug 1196967 - fixed version information

cmd/sti/main.go, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/git/clone.go, pkg/git/git.go, pkg/git/git_test.go
With this `sti build` always streams the output from the `assemble` script to console (so users can see the build progress/warning/non-fatal errors without bumping loglevel).
Additionally I switched 'git' into quite mode (you don't really need to see the git clone command, only errors when the git fails). Also the git command output is now streamed via glog() to have consistent output.
The `assembleOutput=false` will make the output super-silent. Nothing is returned to users except errors.
=> Add --assembleOutput=true to sti build command

pkg/scripts/install.go
This makes it possible for users that are not the user building
the STI image to execute the image.
=> Set permissions of installed scripts to world read/exec

cmd/sti/main.go, pkg/api/printer.go
Produces output:
```console
$ sti build --loglevel=2 -e "FOO=BAR,TEST=BAR" foo bar test 
Base Image:		bar
Source:			foo
Output Image Tag:	test
Environment:		FOO=BAR,TEST=BAR
Incremental Build:	disabled
Remove Old Build:	disabled
Force Pull:		enabled
Quiet:			disabled
Layered Build:		disabled
Docker Endpoint:	unix:///var/run/docker.sock
Docker Pull Config:	/home/mfojtik/.dockercfg
Docker Pull User:	mfojtik
```
(the fields are actually aligned, GH messed this up)
=> Add human-friendly api.Request printer

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/docker_test.go
Allows origin code to pass in DNS lookup info to container launched by STI
=> Allow passing DNS servers and search prefixes to build container

cmd/sti/main.go, pkg/api/describe/describer.go, pkg/api/types.go, pkg/build/interfaces.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go, pkg/git/clone.go, pkg/git/clone_test.go, pkg/git/git.go, pkg/scripts/download.go, pkg/scripts/download_test.go, pkg/scripts/install.go, pkg/test/download.go, pkg/test/git.go, pkg/util/labels.go
This PR will make s2i store more metadata about the source code the image was built from.  This will help debugging problems as you can later, in runtime identify what revision of the app is the container running.
=> Add more metadata into output image

cmd/sti/main.go, docs/cli.md, pkg/build/config.go, pkg/build/strategies/sti/sti.go
This command allows you to rebuild the existing S2I image (if the existing S2I image has the required LABEL(s) set).
Example:
```console
π ~/sandbox/ruby sti rebuild testapp --force-pull=false
Already on 'master-foo'
Your branch is up-to-date with 'origin/master-foo'.
W0626 13:06:29.347093 30851 docker.go:263] The 'io.s2i.scripts-url' label is deprecated. Use "io.openshift.s2i.scripts-url" instead.
W0626 13:06:31.133542 30851 sti.go:127] Clean build will be performed becase of error saving previous build artifacts
I0626 13:06:31.706939 30851 sti.go:393] ---> Installing application source
I0626 13:06:31.708994 30851 sti.go:393] ---> Building your Ruby application from source
I0626 13:06:31.709175 30851 sti.go:393] ---> Running 'bundle install --deployment'
I0626 13:06:37.391292 30851 …
```
=> Add `sti rebuild` command

cmd/sti/main.go, pkg/api/types.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go, pkg/test/docker.go, pkg/util/checkroot.go, pkg/util/checkroot_test.go
If the --no-root flag is specified, the build will fail if the builder does not specify a USER with a numeric id that is not 0.
=> Add flag to prevent builders from running as root

cmd/sti/main.go, pkg/api/describe/describer.go, pkg/api/types.go, pkg/build/config.go
@bparees @soltysh this patch will display following information about builder (if the labels are set):
```console
Application Name:	testapp
Description:		Platform for building and running Ruby 2.0 applications
Builder Name:		Ruby 2.0
Builder Image:		openshift/ruby-20-centos7
Builder Image Version:	00aa786
Builder Base Version:	edab803
Source:			file:///home/mfojtik/sandbox/ruby
Source Ref:		master-foo
Output Image Tag:	testapp
Incremental Build:	enabled
Remove Old Build:	disabled
Force Pull:		disabled
Quiet:			disabled
Layered Build:		disabled
STI Scripts URL:	image:///usr/local/sti
Docker Endpoint:	unix:///var/run/docker.sock
Docker Pull Config:	/home/mfojtik/.dockercfg
Docker Pull User:	mfojtik
```
=> Print builder image labels

pkg/create/templates/scripts.go
Otherwise, when running the image with "docker run ...", we have an error :
Cannot start container [...]: exec format error
Because docker "looks at the first few bytes to determine the type of the file"
See https://github.com/docker/docker/issues/10668 for more
=> Remove empty line at the top of the generated scripts

pkg/api/types.go, pkg/util/labels.go
Adding labels that contain information about the build source.
@bparees @soltysh PTAL
This is the first part of the 'Adding build labels' effort.
Here is the second part: https://github.com/openshift/origin/pull/4079
=> Adding build labels

cmd/sti/main.go, hack/build-test-images.sh, hack/test-integration.sh, pkg/api/types.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/strategies.go, pkg/build/strategies/strategies_test.go, pkg/docker/docker.go, pkg/errors/errors.go, pkg/test/docker.go, pkg/util/user/range.go, pkg/util/user/range_test.go, pkg/util/user/rangelist.go, pkg/util/user/rangelist_test.go, test/integration/images/sti-fake-numericuser/Dockerfile, test/integration/images/sti-fake-onbuild-numericuser/Dockerfile, test/integration/images/sti-fake-onbuild-rootuser/Dockerfile, test/integration/integration_test.go
Adds a flag --allowed-uids to the sti command that takes a comma-separated list of uid ranges, where a range can be:
1) a single number
2) [from]-[to] where [from] and [to] are integers
3) [from]-  a range with no upper bound
4) -[to]  a range with no lower bound
If this argument is specified, S2I checks whether the user specified in the builder image is 
1) numeric
2) is contained within the specified ranges
(For ONBUILD images the check also applies to USER ONBUILD instructions)
If those conditions are not met, the build fails.
=> Add allowed-uids flag to the sti command

pkg/git/clone.go
Found our that the SourceInfo.ContextDir field is not filled by the ContextDir from the Config.
@bparees PTAL
=> Adding context-dir to SourceInfo object

pkg/build/strategies/sti/sti.go
addresses another part of https://github.com/openshift/origin/issues/4127
@jhadvig @soltysh @mfojtik @gabemontero ptal.
I debated just always pulling the previous image, period.  That would avoid the possibility that someone does an incremental build with a stale previous image and picks up bad dependencies/artifacts, but in the end i decided we have "forcePull" for a reason, so the semantics are:
if forcePull is true, the builder AND the previous image (if incremental) are pulled.
if forcePull is false and the previous image does not exist locally, it is pulled.  
if forcePull is false and the previous image does exist, it is used (might be stale)
=> always pull if not present for incremental

pkg/docker/docker.go
when go version is 1.3.3, compile with error:
[root@openshift-144 source-to-image]# make
hack/build-go.sh
++ Building go targets for linux/amd64: cmd/sti
github.com/openshift/source-to-image/pkg/docker
_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/docker.go:407: syntax error: unexpected range, expecting {
_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/docker.go:410: syntax error: argument to go/defer must be function call
_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/docker.go:412: non-declaration statement outside function body
_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/docker.go:413: syntax error: unexpected }
=> fix syntax error: unexpected range for go1.3.3

hack/test-stirunimage.sh
@bparees here's a script for testing sti --run=true
In another git newbie instance, it also includes the cherry picked gofmt related change from test, but the change is the same, so it should be no harm, right?
I'm also working on the vagrant-openshift change to call this script, which of course will be a separate PR.
thanks
=> sti --run=true test

cmd/s2i/main.go, pkg/api/types.go, pkg/git/clone.go, pkg/git/git.go, pkg/git/git_test.go, pkg/test/git.go
This allows you to set `--recursive=false` to disable `git clone --recursive`.
=> Allow to disable --recursive fetch

pkg/tar/tar.go, pkg/tar/tar_test.go, pkg/test/tar.go
Also allows setting the exclusion pattern for tar and allows
specifying whether the source directory should be included in
the path for the tarred files.
=> Expose the CreateTarStream function publicly

pkg/tar/tar.go
When tarring windows paths, we store the windows-style path separators in the tar. If the tar is extracted on a unix system, the separators are not interpreted correctly. However, extracting a tar on a windows machine always works correctly with unix-style path separators.
=> Use unix-style path separators when creating tar files

pkg/scm/git/git.go
Get the whole commit ID hash instead of the short version.
Based on conversation at the end of the https://github.com/openshift/origin/issues/615 issue.
@bparees @smarterclayton PTAL
=> Get the whole commitID hash

pkg/tar/tar.go, pkg/tar/tar_test.go
Here is my (first version of) fix for symbolic links (fixes #290).
PTAL @rhcarvalho 
I want to discuss the following questions:
1) Currently we are supporting only directories, files and now symbolic links. What about other file types? For instance, hard links, devices, etc? Because we don't have any special code that work with it we probably will have bugs when someone will put such files inside an archive.
2) I tried to set atime/mtime of symbolic link when it's restored (like we do for files) but with no luck. We can't use `os.Chtimes()` because it doesn't work with symbolic links and I didn't find a function for that. If we decided to restore mtime/atime for symlinks we should use syscall for that. Probably, this link may be interesting: …
=> [#290] s2i build --incremental=true: fix restore of symblic links.

pkg/build/interfaces.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/sti/usage.go, pkg/build/strategies/strategies.go, pkg/tar/tar.go, pkg/test/tar.go
Origin needs to be able to download and assemble the source
itself and then pass it to s2i. This commit adds changes to
allow an Overrides object to be passed to the s2i initializer
code to provide a custom Downloader.
This also makes changes to allow better reuse of upstream s2i
code and removes a write to disk for the intermediate tar (which
can be streamed instead).
@mfojtik @bparees review, this is part of binary build
=> Allow S2I behavior to be overriden by caller

Godeps/_workspace/src/github.com/docker/docker/pkg/archive/changes.go
This reverts commit edd4961d01fbefca77808e96249cf3cc4900f7d8.
=> Revert "Fixing typo"

pkg/tar/tar.go, pkg/test/tar.go
Adds additional methods to the tar interface to log the files being extracted/archived (similar to -v flag on the tar command). 
Also fixes name truncation when the parent directory is the current directory.
=> Add logging to tar, fix extract when parent dir is .

pkg/api/types.go, pkg/build/strategies/sti/sti.go
This patch will strip the glog prefix from the assemble script that run in container. It should make the logs in OpenShift **much** cleaner.
I also preserved an option to enable the glog programmatically and the glog is on by default for log levels greater than 3.
=> Remove glog prefix from build log messages by default

cmd/s2i/main.go, hack/test-integration.sh, hack/test-stirunimage.sh, pkg/api/describe/describer.go, pkg/api/types.go, pkg/api/validation/validation.go, pkg/api/validation/validation_test.go, pkg/build/config.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/docker/fake_docker.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/scripts/install_test.go, test/integration/integration_test.go
This will replace the --force-pull with --pull-policy option. This option default to "if-not-present" which means that the Docker image will be pull only if it does not exists locally.
Valid options are "always", "never" or "if-not-present".
* `always` will always try to pull the Docker image first and then check if the local image exists
* `if-not-present` will honor the local image and only in case the local image does not exists, it will attempt to pull it
* `never` will never perform pull and always use the local image
Fixes: https://github.com/openshift/source-to-image/issues/273
=> Replace --force-pull with --pull-policy

pkg/build/strategies/layered/layered.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go
The problem is that we should never using `filepath.Join` when constructing the path we later use in container (like assemble path). If this code is called on Windows, the final path will not be UNIX but Windows path, which will lead to stripping all path separators.
Fixes: https://github.com/openshift/source-to-image/issues/314
=> WIP: Stop using filepath.Join on windows

pkg/scripts/install.go
Fixes: https://github.com/openshift/source-to-image/issues/306
=> Print warning when s2i script exists in wrong directory

pkg/tar/tar.go
Fixes: https://github.com/openshift/source-to-image/issues/306
@bparees @csrwng I think increasing the timeout here will help with extracting large files.
=> Increate the timeout when tar closes the stream

pkg/scm/file/download.go, pkg/test/fs.go, pkg/util/fs.go
When specifying a local directory (that is not a git repo), we copy the files from it to a temporary upload/src directory using ```cp -a``` For the contents of the directory to be copied and not the directory itself to be copied, the directory spec must end in "/".
=> Fix copying of local file directory

pkg/api/types.go, pkg/scm/git/git.go, pkg/util/labels.go
Separates the author info and adds committer info so it can be used by Origin code.
=> Add additional fields for author and committer to git.SourceInfo

pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/scm.go, pkg/scm/scm_test.go
@bparees the one small piece of clean up from the origin testing of the clone spec / url validation pull ; there is a short term work around to the caller of MungeNoProtocolURL on the origin side (pkg/generate/git/git.go) (no callers on the source-to-image side).  The origin side change can tolerate MungeNoProtocolURL either prefixing or not prefixing the path with "file://".
We can godeps merge this change and remove the workaround in origin at our convenience.
PTAL when you get the chance - thx
=> don't prepend file:// to url path with MungeNoProto

pkg/build/strategies/sti/sti_test.go, pkg/create/templates/docker.go, pkg/create/templates/scripts.go
i noticed that the generator scripts still use the old /usr/local for assemble, run, etc. so i've changed it to the new localtion /usr/libexec/s2i as mentioned in this [sti-base image PR](https://github.com/openshift/sti-base/pull/60) also modified it in the tests.
my question is, should it be done this way, hard coded or should we set it according to the env variable $STI_SCRIPTS_PATH set in sti-base in case this path changes again?
Later Edit: nvm, found my answer to the question: https://github.com/openshift/source-to-image/pull/302/files#r41652962
=> changed /usr/local to /usr/libexec/

cmd/s2i/main.go, docs/cli.md, pkg/api/types.go, pkg/api/types_test.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/fake_docker.go, pkg/docker/test/client.go, pkg/tar/tar.go, pkg/test/tar.go, pkg/util/injection.go, pkg/util/injection_test.go, test/integration/integration_test.go, test/integration/scripts/.sti/bin/assemble
Trello: https://trello.com/c/m5bPxwh4/643-8-allow-to-consume-secrets-in-builds
How this works?
```console
$ echo supersecretstuff > /tmp/foo/secret
$ s2i build -p never --loglevel=5 --inject /tmp/foo:/tmp/bar \
file://${GOPATH}/src/github.com/openshift/sti-ruby/2.2/test/rack-test-app \
centos/ruby-22-centos7 testapp
```
What will happen is that the content of `/tmp/foo` folder will get injected (copied) into the container where the `assemble` script runs into the `/tmp/bar` directory. Assemble script can then read the "secret" file from there. The `UploadToContainer` approach allows is to copy any file into any arbitrary location in the container, which is great, because you can replace any file in container (or write to any directory)...
The drawback of this solution is that the file …
=> Support injecting files into a container that runs assemble script

hack/rebase-to-origin.sh
Tired of manual rebase to origin? Try this handy script :-)
This script assumes that the "origin" is cloned into $GOPATH/src/github.com/openshift/origin.
This script will create a new branch, so make sure the "origin" HEAD is the latest master.
After you invoke this script, the branch and the commit will be created with proper commit message, ready to push and create a PR from it.
=> Add rebase-to-origin.sh script

pkg/build/strategies/sti/sti.go, pkg/util/injection.go
Fixes: https://github.com/openshift/source-to-image/issues/397
Thanks to @php-coder for debugging this problem! Can you please review this?
This will basically stop the build when the injection fails. It also provides 'better' error to user:
```console
E0128 09:52:23.853183 09625 injection.go:99] The destination directory for "/data/src/github.com/openshift/source-to-image/docs" injection must exists in container ("/root/foo")
I0128 09:52:24.776407 09625 main.go:326] An error occurred: API error (404): lstat /var/lib/docker/devicemapper/mnt/664dc416e71434fab5fae2324fdcc6125c141d3643b691442a250788b064e243/rootfs/root/foo: no such file or directory
```
=> Fail the build when destinationDir does not exists during injection

pkg/docker/util.go, pkg/tar/tar.go, pkg/util/fs.go
Misc minor improvements that I've made during working on #397:
- `fs.Chmod()`: don't try to change file mode on Windows
- `fs.CreateWorkingDirectory()`: change prefix of the temp dir from sti to s2i
- `tar.StreamDirAsTar,StreamFileAsTar()`: don't try to change file mode on Windows
- `tar.CreateTarStreamWithLogging()`: don't swallow errors
- `tar.CreateTarStreamWithLogging()`: quote file names in error message
- `util.StreamContainerIO()`: fix typo in godoc
@mfojtik PTAL
=> Misc improvements

hack/rebase-to-origin.sh, hack/util.sh
Changes for `rebase-to-origin.sh`:
- fix `sed` invocation under Linux
- prefer single quotes
- replace `find -exec rm` with `find -delete`
- fix typo in comment
@mfojtik @bparees PTAL
@mfojtik I don't see the reason of using `-m2` in `grep -m2 -A2 'openshift/source-to-image' Godeps.json`. Could you explain why?
=> rebase-to-origin.sh: unbreak under Linux

docs/debugging-s2i.md, pkg/build/strategies/sti/sti.go, pkg/scripts/environment.go
@bparees FYI
This is a leftover from deprecating the `.sti` in `api.ScriptSource`. Also I'm adding glog.Infof() here because I think seeing that the environment of the build is going to change based on provided file is important to user to confirm the file is actually picked up and the env vars are used.
=> Deprecate .sti/environment

cmd/s2i/main.go, pkg/cmd/util.go
Go prints a stack trace of all goroutines by default on SIGQUIT, except those related to the runtime.
To include all goroutines, set GOTRACEBACK=2 or GOTRACEBACK=crash.
This custom handler suppresses Go's default behavior.
http://stackoverflow.com/a/35290196/4804690
=> Remove custom SIGQUIT handler

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
This allows to take artifacts from an image with a tag different than the output tag.
The default behavior is still to use the same tags.
This is needed to fix a regression in incremental builds OpenShift: https://github.com/openshift/origin/issues/7708
=> Add support for custom tag for incremental builds

pkg/build/strategies/sti/sti.go
- Let the function that created the pipe arrange freeing resources
(we shall not rely on extractFunc being executed).
- Remove unnecessary if clause.
=> Defer closing all ends of pipe

cmd/s2i/main.go, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/run/run.go
Adds a flag to the s2i build command to allow specifying a set of capabilities to drop when executing a container.
Example:
```
s2i build --cap-drop=SETGID,SETUID https://github.com/myname/myrepo.git myco/builder:latest my-app
```
=> Allowing dropping capabilities when running a container

pkg/util/timeout.go
In case there is a time out, the goroutine would panic on sending on a
closed channel.
@bparees @mfojtik PTAL
@mfojtik here's the example you asked: http://play.golang.org/p/N5ANWaIdt6
=> Close channel only after last send

Godeps/Godeps.json, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/.travis.yml, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/AUTHORS, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/Makefile, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go
I'm gonna need code that is in the version in origin and not in the old version we had here (`AttachToContainerNonBlocking`)
Sending as separate PR to not pollute the diff of #430 with all these changes.
@bparees ptal
=> Bump dockerclient to match version in origin

pkg/docker/docker.go
No need to spawn a goroutine just to block waiting for it do be done.
Extracted this away from my other changes to make it easier to review / test the behavior.
@bparees @gabemontero could you guys have a look?
I checked this change with this command:
```console
$ s2i build https://github.com/bparees/incremental-app centos/ruby-22-centos7 incr-test --loglevel=5 --run
...
The image incr-test:latest has been started in container 4fc3f034a41c833f7339594caa526e61256883ed01d1f70b7a5c48f93ea67a5f as a result of the --run=true option.  The container's stdout/stderr will be redirected to this command's glog output to help you validate its behavior.  You can also inspect the container with docker commands if you like.  If the container is set up to stay running, you will have to Ctrl-C to exit …
```
=> Wait for signal in the same goroutine

pkg/tar/tar.go
Error checking should be done earlier, and if there's an error creating
a file we should not try to use the file.
Error creating a file is an exceptional condition, can happen for lack
of permissions, full disk, etc. Calling file.Close() on a nil File
pointer would panic.
=> Check error before deferring calls that use file

pkg/api/validation/validation.go, pkg/api/validation/validation_test.go, pkg/build/strategies/sti/sti_test.go, pkg/scm/empty/noop.go, pkg/scm/scm.go, pkg/scm/scm_test.go
@bparees PTAL
These are the source-to-image changes needed for build config with no inputs.
They stem from [this call in origin](https://github.com/openshift/origin/blob/master/pkg/build/builder/sti.go#L208) failing a source strategy build.
Also, I made this change *origin* only, and did not add any options to `s2i`.  The `s2i` user minimally still should point that command to a local directory with scripts.
=> allow for no source URL (defer download to assemble script)

pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/docker/docker_test.go, pkg/ignore/ignore_test.go, pkg/scm/git/clone_test.go, pkg/scm/git/git_test.go, pkg/scripts/install_test.go, pkg/tar/tar_test.go
- The majority of the changes in this commit is about removing redundant
trailing '\n', since t.Logf & related methods automatically handle
trailing new lines, and essentially ignore that extra line we're
adding.
- Replace several usages of '%s' where '%q' would be more useful.
- Fix cases where the arguments to format the string were incorrectly
part of the string itself, not arguments.
=> Fix test messages

pkg/run/run.go
We focused on translating one specific error case, and missed returning
any other error, returning nil instead.
Also document why we recreate a ContainerError, and preserve all
original fields except the one we intend to change.
=> Do not ignore errors

pkg/docker/docker.go
@mfojtik i'm seeing us hit the 10s timeout in the push job here:
https://ci.openshift.redhat.com/jenkins/job/push_images_s2i/290/console
```
make test TARGET=centos7 VERSION=9.0 TAG_ON_SUCCESS=true
I0323 21:48:02.641485 09671 clone.go:32] Downloading "/tmp/images/wildfly-90/9.0/test/test-app" ...
I0323 21:48:02.665269 09671 install.go:236] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I0323 21:48:02.665303 09671 install.go:236] Using "run" installed from "image:///usr/libexec/s2i/run"
I0323 21:48:02.665324 09671 install.go:236] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
E0323 21:48:12.675097 09671 main.go:336] An error occurred: calling the function timeout after 10s
```
so i think maybe we should raise the limit.  ptal.
=> raise default docker timeout

pkg/docker/docker.go
This is a quick on-spot fix, would be nice to actually rework the overall implementation to avoid this hackish solution.
The problem is that `STI.Save` (for saving artifacts) calls `RunContainer` with `opts.OnStart` set to a function that reads from the read half of a pipe, while the write half is set as the container stdout. Docker (go-dockerclient) won't close the container's output and error streams upon termination (expected behavior), so `OnStart` will never terminate, it will block forever waiting for more data to be read.
With `OnStart` blocked, `RunContainer` is blocked, and `STI.Save` never returns, thus the deferred call to close the pipe halves is never executed, thus the deadlock.
@bparees this is what we're all waiting for these days, it fixes the hang we were seeing with …
=> Fix deadlock condition

cmd/s2i/main.go, contrib/bash/s2i, hack/update-generated-completions.sh
Fixes: https://github.com/openshift/source-to-image/issues/415
@bparees PTAL
The usage here is to run:
`$ s2i genbashcompletion > completion_file.sh`
It is also possible to add `eval $(s2i genbashcompletion)` into `.bashrc` IMHO.
`EDIT:` Added generated completion per @soltysh request :-)
=> Add genbashcompletion sub-command

pkg/docker/util.go, pkg/docker/util_test.go, pkg/util/user/rangelist.go
When checking whether a user is in the allowed range, a USER directive with uid:group is now allowed.
=> Handle user:group specification in Dockerfile

cmd/s2i/main.go, docs/cli.md, pkg/api/describe/describer.go, pkg/api/types.go, pkg/api/types_test.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/cmd/util.go
Fixes: https://github.com/openshift/source-to-image/issues/417
@bparees this one is tricky :-) Basically, you can specify a multiple environment variables, by providing multiple `-e FOO=BAR` flags. The syntax we supported before was that you can use something like: `-e FOO=BAR,TEST=FOO`. 
So this is introducing a backward incompatible change. I wonder if we want to make it backward compatible (basically do additional string.Split() in the `Set()` function) or leave it as this (which is consistent with other flags).
=> Use cobra for parsing multiple env variables

README.md
I think it looks better to quote literals.
=> README.md: Add some extra backtick quotation

cmd/s2i/main.go, contrib/bash/s2i, docs/cli.md, pkg/api/describe/describer.go, pkg/api/types.go, pkg/api/types_test.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/util/injection.go, pkg/util/injection_test.go, test/integration/integration_test.go
Fixes: https://github.com/openshift/source-to-image/issues/416
This PR add ability to define [bind mounts](https://docs.docker.com/engine/userguide/containers/dockervolumes/#adding-a-data-volume) for container where the assemble runs.
Note that this is different from "inject", because specifying a bind mount will replace the content of the directory inside the container, where "inject" will only add/overwrite the files.
One cool side-effect here is that you are able to "build" sources using S2I, but you don't have to care about the output image (allows to build jars, binary artifacts, etc...)
Example:
```console
$ s2i build --loglevel=5 -v $(pwd):/opt/app-root/src . centos/ruby-22-centos7 hello-world-app
```
=> Add support for bind mounts

README.md, cmd/s2i/main.go, docs/cli.md, docs/debugging-s2i.md, pkg/create/templates/test.go, pkg/errors/errors.go
Polish documentation a bit:
- use `--pull-policy` instead of `--force-pull` option
- update usage after changing the default value of `--force-pull` from `true` to `false`
- replace usage of deprecated `openshift/wildfly-8-centos` image by `openshift/wildfly-81-centos7`
- replace `.stifile` by `.s2ifile` in `--use-config` option description
PTAL @bparees
=> Replace usage of --force-pull option

pkg/util/labels.go
When we're using `--copy` we lose meta information from git.
Prior this change we put label `"io.openshift.s2i.build.commit.author": " <>"` to resulted image.
PTAL @bparees
=> Add commit.author label only when author is non-empty.

hack/rebase-to-origin.sh
Previous version never expanded the * and consequently never deleted
files from $origin_s2i_godep_dir, and we got no warning because of '-f'.
=> Fix globbing in hack/rebase-to-origin.sh

hack/common.sh
The condition should test for `go1.4` and use `${key} ${val}`, while `go1.5` and `go1.6` should use `${key}=${val}`.
The actual test could consider versions prior to go1.4, but I think we don't care about them, i.e., we require go1.4+?
=> Fix ldflag logic

hack/build-cross.sh, hack/build-go.sh, hack/build-release.sh, hack/common.sh, hack/extract-release.sh, hack/test-go.sh, hack/update-generated-completions.sh, hack/util.sh
Gradually getting rid of 'sti'.
=> Replace 'sti::' with 's2i::' in Bash scripts

CONTRIBUTING.md, hack/build-base-images.sh, hack/build-cross.sh, hack/build-go.sh, hack/build-release.sh, hack/build-test-images.sh, hack/common.sh, hack/extract-release.sh, hack/install-tools.sh, hack/test-go.sh, hack/test-integration.sh, hack/update-generated-completions.sh, hack/verify-bash-completion.sh, hack/verify-gofmt.sh, hack/verify-golint.sh, hack/verify-govet.sh, images/release/Dockerfile
This is a careful replacement of `STI_([A-Z_]+)` with `S2I_$1` in all
*.sh files, plus references to those env vars in other files.
=> Replace STI_* env vars with S2I_*

pkg/build/cleanup.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/scripts/environment.go, pkg/scripts/install.go, pkg/tar/tar.go, pkg/util/labels.go
- `pkg/docker/docker.go(dumpContainerInfo)`: fix a typo in comment
- `DefaultCleaner.Cleanup()`: add comment with explanation how it works
- Use `glog.Info` instead of `glog.Infof`
- `DefaultCleaner.Cleanup()`: show warnings when error happened
- `DefaultCleaner.Cleanup()`: use `%q` modifier
- `strategies/layered/layered.go(CreateDockerfile)`: use `--` for separating options from directories
- `strategies/layered/layered.go(CreateDockerfile)`: extract variable
- `strategies/layered/layered.go(CreateDockerfile)`: use variables instead of slice
- `pkg/build/strategies/layered/layered.go`: add missed bracket to comment
PTAL @bparees
CC @rhcarvalho
=> Minor improvements

doc.go, pkg/api/types.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/onbuild/onbuild_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/scm.go, pkg/scripts/download.go, pkg/scripts/download_test.go, pkg/tar/tar.go, pkg/tar/tar_test.go, pkg/util/fs.go, pkg/version/doc.go, pkg/version/version.go, test/integration/doc.go
Includes:
- Changes to commentaries to follow godoc conventions;
- Fix shadowing of identifiers;
- Missing error checks;
- Fix incorrect usages of fmt.Print* functions;
- Initialize struct literals from other packages using explicit field
names;
- Rename variables (not used in origin) to follow Go conventions.
=> Apply several small fixes from go vet and others

pkg/docker/docker.go, pkg/docker/util.go, pkg/util/glog/glog.go
Continuation of work done in Origin, but ensures that we aren't using
glog for our core messages for end users in builds.
@mfojtik @bparees fixes part of https://github.com/openshift/origin/pull/8924
=> S2I needs to selectively log to stderr instead of glog

.travis.yml, Makefile, hack/install-tools.sh, hack/rebase-to-origin.sh, hack/util.sh, hack/verify-gofmt.sh, hack/verify-golint.sh, hack/verify-govet.sh
Summary:
- Add 'make verify' to Travis.
- Fix verify-golint.sh: old invocation would not work unless GOPATH is a
single directory.
- Fix verify-govet.go: 'go vet' does not take flags, should use 'go tool
vet'.
- Fix early termination of hack/verify-govet.sh.
- Enable 'go vet' in 'make verify'; will prevent introducing problems
detected by the vet tool in future PRs.
- Make sure golint is installed in Travis.
- Improve install-tools.sh, parity with the one in openshift/origin.
- s/os::util::sed/s2i::util::sed for consistency.
- Reimplement/simplify find_files, now called s2i::util::find_files, and
use it in all scripts consistently.
- Suggest autocorrection for gofmt, as seen in openshift/origin.
- Do not check Go version (verify-*.sh should be run no matter the Go
version?!).
- Do not …
=> Fix hack/verify-*.sh and improve other scripts

pkg/util/glog/glog.go
Fix logging regression after #500
Before this patch:
```
I0519 17:35:08.051810 02152 glog.go:50] --> Uploading ["/tmp/s2i052311221/upload/scripts/run" "/tmp"] to %!q(MISSING) ...
```
After this patch:
```
I0519 17:42:06.734580 03500 glog.go:50] --> Uploading "/tmp/s2i886301399/upload/scripts/run" to "/tmp" ...
```
PTAL @bparees @smarterclayton
=> Fix  passing of the arguments in our Logger implementation

pkg/build/strategies/sti/sti.go
Also include a tag of previous image to the message.
This is a fix for the small regression that was added in #501: it started to show error message:
```
error: Error retrieving previous image's metadata: no such image
```
But it didn't do anything else, so nothing was broken.
PTAL @bparees
=> Fix error message about retrieving previous image's metadata for non-incremental build

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
This fixes a bug introduced in https://github.com/openshift/source-to-image/pull/501
@bparees @php-coder
=> Pass --env variables to the build container

pkg/tar/tar.go
Avoids writing header when directory being tarred itself is a symlink
=> tar: fix panic when dir is symlink

README.md
Added documentation to the README.md for installing from our releases.  Uses the "latest" url from GitHub.
Fixes https://github.com/openshift/source-to-image/issues/372
@bparees ptal, lmk if you want to reword something
=> Added documentation for installation with release binaries.

cmd/s2i/main.go, pkg/docker/docker.go, pkg/docker/docker_test.go
Instead of leaving the name blank and letting the Docker daemon name
containers with random strings like 'lonely_thompson', we give proper
names so that we can identify and filter containers created by S2I
later.
Names take a fixed prefix, 's2i_', and a random suffix. The builder
image is also used to compose the container name, replacing with
underscores characters that would be invalid for a container name.
Example:
```console
$ s2i build \
git://github.com/openshift/ruby-hello-world \
centos/ruby-22-centos7 \
hello-world-app
```
The above creates a temporary container named
's2i_centos_ruby_22_centos7_397cfecd'.
-----------------------------------------
Fixes #395.
=> Name containers created by s2i explicitly

cmd/s2i/main.go, pkg/api/types.go, pkg/build/cleanup.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/entrypoint.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/sti.go, pkg/config/config.go, pkg/create/create.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/ignore/ignore.go, pkg/run/run.go, pkg/scm/empty/noop.go, pkg/scm/file/download.go, pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/scm.go, pkg/scripts/download.go, pkg/scripts/environment.go, pkg/scripts/install.go, pkg/tar/tar.go, pkg/util/fs.go, pkg/util/glog/glog.go, pkg/util/injection.go, pkg/util/labels.go
@smarterclayton @bparees @csrwng 
- Added additional methods to glog mock util to limit impact when porting other libraries currently using standard glog
- Add flushing to file based loggers (doesn't really matter for stderr, but if you changed to use a real file, it could)
Question: I tied --loglevel to the level maintained by the toFile logger created by toFile. This obviates some of the logic of pkg/util/glog.go:V(int32) because file.level will always match vanilla golog's Level. That is, V(#) will never decide to send user output to standard glog instead of the file output.
The alternative, leaving toFile's file.level at a constant 2, didn't seem like a useful notion here *unless* you want golog's prefix to be included on Info and above. However, even if you did, the stack element …
=> Migrating s2i to use glog mock library

README.md, docs/runtime_image.md
- s/Golang/Go/
- Make similar paragraphs similar, include the same list of languages.
The paragraph in docs/runtime_image.md contains more detailed
information.
- Spurious whitespace changes.
=> Fix some nits in documentation

pkg/api/describe/describer.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/postexecutorstep_test.go, pkg/build/strategies/sti/sti.go, pkg/docker/docker.go, pkg/docker/fake_docker.go, pkg/run/run.go
fixes https://github.com/openshift/source-to-image/issues/475
this basically reimplements https://github.com/openshift/source-to-image/pull/476 but ensures the entrypoint in the final committed image is not changed to "env".
=> override entrypoint to env during assemble

pkg/util/injection.go
Running origin's test/extended/builds/secrets.go, I was receiving a consistent error on the source buildconfig with secrets.  
The build would always fail at this point:
```
...
I0721 19:15:25.305187       1 tar.go:263] Adding to tar: /tmp/s2i-build790441331/upload/src/Gemfile as src/Gemfile
I0721 19:15:25.305238       1 tar.go:263] Adding to tar: /tmp/s2i-build790441331/upload/src/config.ru as src/config.ru
E0721 19:15:25.546017       1 util.go:96] truncate: cannot open '/tmp/..data' for writing: Is a directory
```
Peering into the builder container, this ..data path is a **symlink** to a directory. In go, os.IsDir(symlinkFileInfo) == false even if it points to a directory. The existing check in ExpandInjectedFiles(api.VolumeList) for IsDir() returned false, allowing the build process to …
=> Fixing s2i dir truncate error

pkg/tar/tar.go
Post bump, this should fix origin 10009. 
StreamFileAsTar makes an attempt to chmod the rm-injections script to 666 before injecting it with a tar stream, but StreamFileAsTarWithCallback was actually setting these permissions on the primordial source for rm-injections. 
Before this PR, rm-injections ended up as root:root 600 in the build container. Now it should be 666 and source-able by the default user.
=> Fixing permission issue during rm_injections

pkg/errors/errors.go, pkg/scm/git/clone.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/scm.go, pkg/scm/scm_test.go, pkg/test/git.go
This fixes an error when the git repo is empty, e.g. the user only ran
`git init`.  If the repo is empty, we use system copy commands instead
of git commands, and warn the user.
Also added warnings for if there is a .git directory in the project, but
a Git binary is not installed.
Currently working on tests, just posting this for discussion
@bparees 
Old output, git installed:
```
---> Installing application source ...
ERROR: cp: cannot stat '/tmp/src/.': No such file or directory
ERROR: An error occurred: non-zero (13) exit code from openshift/ruby-22-centos7
```
Old output, git not installed:
```
---> Installing application source ...
---> Building your Ruby application from source ...
WARNING: Rubygem Rack is not installed in the present image.
Add rack to your Gemfile in order to …
```
=> Added checks for existing content is git repo

pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go
@php-coder ptal, the current output looks horrible because npm (among other things) uses stderr for its output, so you end up with `ERROR: some normal npm operation` in your normal s2i output.
this seems like the lesser of two evils to me right now.
=> log stderr as info messages

pkg/build/strategies/sti/sti.go
Before this change S2I failed to inspect runtime image (when we're invoked from OpenShift and tried to do extended build with the scripts inside of runtime image):
>I0808 09:39:54.899522       1 docker.go:459] error inspecting image 172.30.253.131:5000/extended-test-extended-build-1ecb2-ry755/jvm-runner-with-scripts@sha256:f4a82128571de55bb2a4ad30a13e87a9caf75aa134e00cf8eb7e67e17384f425: no such image
>I0808 09:39:54.899631       1 docker.go:446] Image "172.30.253.131:5000/extended-test-extended-build-1ecb2-ry755/jvm-runner-with-scripts@sha256:f4a82128571..." not available locally, pulling ...
>I0808 09:39:54.900948       1 docker.go:468] Pulling Docker image 172.30.253.131:5000/extended-test-extended-build-1ecb2-ry755/jvm-runner-with-scripts@sha256:f4a82128571de55bb2a4ad30a13e87a9caf75aa1 …
=> Use runtime authentication in installer

hack/rebase-to-origin.sh
PTAL @bparees @PI-Victor @mfojtik
=> hack/rebase-to-origin.sh: exclude pkg/docker/test dir and preserve LICENSE file

pkg/scm/git/git_test.go, pkg/scm/scm_test.go, pkg/test/git.go
This allows multiple unit tests to use these functions, which were
previously copy/pasted between them.
@bparees @php-coder ptal?
=> Moved createLocalGitDirectory to test package

hack/rebase-to-origin.sh
This allows us to use Git testing utilities in origin.
Perhaps in the future we should merge the Git utilities that are spread between the projects?
Sorry for the quick one-liners :)
=> Removed pkg/test from excluded packages in script

pkg/build/strategies/sti/sti.go
Bug 1364965
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1364965
Detailed explanation when gathering build output, the intent is to
ignore expect "errors" like EOF, but an EOF error showed up in the logs;
we could not decipher actual type besides io.EOF that arrived, but we augmented
to log to print the type; next time it arrives, we can add that type to the check list
@bparees PTAL
=> s2i: unexpected error entry in s2i build logs

cmd/s2i/main.go, hack/test-stirunimage.sh, pkg/api/describe/describer.go, pkg/build/config.go, pkg/docker/util.go
Bug 1366475
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1366475
Detailed explanation
an attempt to pull the builder image to obtain labels was made; the correct thing was
to pull the locally build image we were rebuilding
@bparees @php-coder PTAL
=> s2i: s2i rebuild broken

pkg/docker/docker.go
related to Bug 1370265
but refactored pulls to isolate default timeout change from waitgroup change ... separate pull coming for that 
@bparees @csrwng @rhcarvalho PTAL
=> bump default docker timeout

pkg/api/types_test.go
Adding a break is a better manner though in a test case, just a nit.
=> if found = true, add break is better

pkg/build/strategies/sti/sti.go
Calling wg.Done() does not "cancel" the WaitGroup, it does introduce a
bug in which depending on timing the WaitGroup counter might go
negative, what should never happen.
Would be nice to rewrite the method to be correct concurrent code, but
for now should be enough to avoid the panic condition and note that
there is a potential leak.
---
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1370265
=> Fix WaitGroup usage

pkg/create/templates/test.go
container_ip is unbound variable, it is a function that has to be called
after fixing this the script correctly executes with `set -u`
=> [test/run] fix unboud variable in the template

pkg/scm/git/git.go
When a ssh url is passed to os.Stat in Windows, the error returned is something other than  ErrNotExist, which results in an error when 'oc new-app' is called with a git url in Windows.
With this change, any error returned by os.Stat will result in us assuming the file doesn't exist.
=> Change file exists check to any error returned by os.Stat

pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/docker/util.go
=> bz1373281 allow >2 slashes in docker URI

pkg/create/create.go, pkg/create/templates/test.go
The build script neds a `git` repository, so the test script run [`git init`](https://github.com/luiscoms/source-to-image/blob/master/pkg/create/templates/test.go#L60)
But when an error occurs on build the script does not clean the `.git/` folder correctly.
To avoid git errors I just add a `.gitignore` file on test folder.
=> Add gitignore on create

pkg/api/describe/describer.go, pkg/api/types.go, pkg/api/validation/validation.go, pkg/api/validation/validation_test.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/postexecutorstep_test.go
Needed for https://trello.com/c/HB9IwGj5/925-5-add-arbitrary-labels-to-docker-images
Work in progress because we probably need to discuss how the API should look like in order to support autogenerated values (e.g. SCM commit hash) in the future.
=> Add support for custom image labels

pkg/tar/tar.go, pkg/test/tar.go
This PR has two commits:
1) fix unbuffered channel and allow detection of expired timer in goroutine
- resolves an issue whereby a goroutine would hang/leak if a timer expired (and also checks within the goroutine to see if the timer has expired according to reccomended practice)
2) add a function ExtractTarStreamFromTarReader which is just like ExtractTarStreamWithLogging but accepts a tar.Reader-like object.  This is a prereq for cleanup in origin/pkg/bootstrap which should use this code.
=> Add ExtractTarStreamFromTarReader

cmd/s2i/main.go, pkg/api/types.go, pkg/build/strategies/layered/layered.go, pkg/build/strategies/onbuild/onbuild.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, test/integration/integration_test.go
This PR adds additional build information so that S2I can tell OpenShift a couple of things:
Why did the build fail. (besides fetch source, [which is implemented on the OpenShift side], container commit, builder image pull, runtime image pull, assemble runtime failed, assemble failed, etc. )
It's related to: https://github.com/openshift/origin/pull/10817
=> Additional build information

pkg/build/strategies/sti/sti.go, pkg/util/status/build_status.go
i've confused !isMissing with isMissing, so the failure reason for this should just be a generic one.
We also don't fail for missing dependencies, but we continue the build with the layered build strategy.
=> Replace wrong failure reason for assemble failed

test/integration/integration_test.go
As fas as the git history can tell, the constraint was never referenced
by any script, never used.
```
$ go vet test/integration/integration_test.go
test/integration/integration_test.go:1: invalid non-alphanumeric build
constraint: integration,!no-docker
```
=> Remove invalid build constraint

pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1390749
If an error occurs in RunContainer that is not a timeout error or a container error, then we wait indefinitely instead of returning an error.
I was able to easily reproduce the hang by simulating errors at different points in RunContainer. I also didn't see a case where a non-nil error should result in us still waiting for the WaitGroup to be done.
=> Fix hang in s2i strategy by avoiding wait on an error

docs/builder_image.md
The pushd and popd commands in the example for save-artifacts example emit output to standard out.  This will corrupt the tar stream, and prevent the reuse of the saved artifacts.
=> Corrected save-artifacts example to prevent tar stream corruption.

pkg/docker/doc.go, pkg/docker/docker.go
Miscellaneous improvements:
- Send on receiveStdout would block forever in goroutine when
holdHijackedConnection returns earlier.
- We should be updating createOpts.HostConfig.ShmSize before we log
createOpts.HostConfig.
- Pkg doc was outdated.
=> Goroutine leak, logging and pkg doc

test/integration/integration_test.go, test/integration/scripts/.s2i/bin/save-artifacts
Ensure the build takes no more than `DefaultDockerTimeout`, what would
suggest that S2I got stuck waiting for the timeout.
This is a regression test for #301.
I've applied this patch to 12908b75a9d965425ef35a84d729f750f38eeb72 (before @jim-minter's fix) and seen the test fail:
```console
$ hack/test-integration.sh -run=TestIncrementalBuildAndRemovePreviousImage
Running integration tests ...
=== RUN   TestIncrementalBuildAndRemovePreviousImage
[...]
I1204 18:33:58.346799   28390 tar.go:434] Extracting/writing /tmp/s2i614376474/upload/artifacts/save-artifacts-invoked
I1204 18:33:58.346864   28390 tar.go:403] Done extracting tar stream
I1204 18:35:58.879113   28390 docker.go:948] Removing container "48a1c0b42ae492612affc572080b4b619a32e549277f4349ab1f6678bef0a44b" ...
[...]
--- FAIL: …
```
=> Add regression test for incremental builds

CONTRIBUTING.md, hack/test-go.sh
`FOO=${FOO:-value}` sets FOO to 'value' if it is null (empty) or unset,
whereas `FOO=${FOO-value}` (without the colon) sets FOO only when FOO is
unset.
`FOO= hack/test-go.sh` is equivalent to `FOO="" hack/test-go.sh`, so
prefer to mention the shorter form.
Let the go tool pick the default cover mode.
Since -coverprofile implies -cover, we don't need to test S2I_COVER when
OUTPUT_COVERAGE is given.
=> Make test environment variables work as advertised

pkg/scm/git/git.go
if ` err == nil`, it is useless to output `err` info.
=> output error when err != nil

pkg/tar/tar.go
=> ChmodAdapter: don't set hdr.Mode early as subsequent lines still need to read it

hack/windows/Vagrantfile
@bparees, turns out I was using the wrong AMI for the RHEL part of the Windows CI.  I haven't got to the bottom of what the difference is between the two, but it repeatedly works with inst and fails with deps.  Please merge and I'll re-enable the CI.
=> use rhel7:inst AMI for Windows CI, to match RHEL CI

LICENSE
This change simply replace the contents of the LICENSE with:
curl https://www.apache.org/licenses/LICENSE-2.0.txt -o LICENSE
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Use the latest text version of the Apache 2.0 License

README.md, cmd/s2i/main.go, docs/cli.md, hack/test-stirunimage.sh, pkg/create/templates/scripts.go, pkg/scm/scm.go, test/integration/integration_test.go
Both protocols are "smart" and should have similar performance.
HTTPS is encrypted, while the Git transport is plaintext.
HTTPS verifies the certificate of the server.
The first commit is taken from #646, then I went ahead and updated other examples and tests that clone GitHub repos.
=> Prefer using https:// instead of git://

.travis.yml, pkg/scm/git/git_munge_test.go
This changes the build to:
* Always build with the latest minor version of the last two (supported upstream) major releases of Go (currently the latest minor version in the 1.6 and 1.7 series)
* At present, this is building with 1.6.3, which seems to be a bug in Travis somewhere (1.6.4 is available)
* It does correctly build with 1.7.4
* Build using the latest major version (1.8 pre-release) from the Golang git repository, but allow failures, so that we have early warning in case there are any problems due to changes in Go itself
=> Build with latest available Go minor versions & tip

README.md
I added a formula for source-to-image to Homebrew (https://github.com/Homebrew/homebrew-core/pull/8729). It means the installation on OS X is much easier now.
=> Add installation instructions for Homebrew (Mac)

README.md
the current link to the ONBUILD docs on dockerhub, https://docs.docker.com/reference/builder/#onbuild , is no longer working,  looks like they changed the location of those docs
=> update ONBUILD docs link to non-breaking link

pkg/build/strategies/layered/layered.go, pkg/build/strategies/layered/layered_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go
MustCompile is meant to simplify initialization code (package var and
init), and may panic. In runtime we should use Compile.
https://talks.golang.org/2014/readability.slide#9
Closes #613.
=> Fix misusage of regexp.MustCompile

README.md
The Ruby example doesn't work - there's no image at `openshift/ruby-23-centos7`. It's now at `centos/ruby-23-centos7`.
=> Ruby 2.3 image has moved

cmd/s2i/main.go, hack/test-stirunimage.sh, pkg/api/describe/describer.go, pkg/api/types.go, pkg/build/strategies/sti/sti.go
These flags are handled when they are passed to Docker. See [here](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)
Fixes #587 
@bparees ptal?
edit:
My branch was pretty far behind. After the rebase, it looks like we don't check for the ':' character in filepaths. This means we need only change the call to strings.LastIndex() to strings.IndexAny(), so that we split on the first ':'
=> Added a check for :z :Z SELinux flags in Volumes

hack/common.sh
Allows running in linux distros that do not have glibc, for example
Fixes #727
=> Make s2i binaries static

pkg/build/strategies/sti/sti.go
Checks and pulls an image before executing a script. This should already be happening when the build strategy gets created. However, there may be some time between the time the strategy is created and the time an assemble script is actually run. In that time the image may be garbage collected.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1446925
=> Pull image before executing S2I script

docs/builder_image.md
I'm not sure if its markdown or an HTML problem but "test/run" with a slash in the anchor isn't working.
=> fix anchor for testrun

pkg/tar/tar.go, pkg/tar/tar_test.go
also bug https://bugzilla.redhat.com/show_bug.cgi?id=1479130
=> ensure files from the tar stream are created with proper permissions

docs/builder_image.md, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/docker/util.go
This PR adds support for the assemble-user label in Dockerfile.
Using this label enables the user to determine a different user to assemble the image than the runtime user.
This is needed in images such as standalone PHP, that the artefacts (PHP pages) should not be writable or owned  by the same user running the daemon.
This directive is already supported by s2i cli, and this only adds the support to define this through a label called `io.openshift.s2i.assemble-user`.
The order here is: first the defined assemble-user in cli. If this is not defined, then searches for the label in the image. 
If nothing is defined, the common workflow (with no AssembleUser) will follow.
Thanks!!
=> Add support for assemble-user label

pkg/create/create.go, pkg/create/templates/test.go
- Remove spurious newlines at the beginning of files
- README.md and index.html are no longer executable.
=> Minor fixes to create template

pkg/docker/docker.go
Add force remove option to cleanup failed build containers when running a layered build.
Related to https://github.com/openshift/origin/pull/17283
=> Add force remove option to layered image builds

pkg/api/validation/validation.go, pkg/api/validation/validation_test.go
Validates the output tag argument using docker's validation code.
Output:
```
$ s2i build . openshift/origin-release:golang-1.8 MyImage:Tag
ERROR: Invalid value specified for "tag": repository name must be lowercase
...
[ command help ]
```
Fixes https://github.com/openshift/source-to-image/issues/826
=> Validate image tag on build

pkg/docker/util.go
Since the code does not rely on docker's engine-api now, this hack should also be removed.
=> Remove the out-of-dated docker engine-api related hack

pkg/api/describe/describer.go, pkg/build/strategies/sti/postexecutorstep.go, pkg/build/strategies/sti/postexecutorstep_test.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/sti/sti_test.go, pkg/build/strategies/strategies.go, pkg/docker/docker.go, pkg/docker/util.go, pkg/scm/git/git.go, pkg/scm/git/git_test.go, pkg/scm/git/url_test.go, pkg/scripts/install_test.go, pkg/tar/tar.go, pkg/util/fs/fs.go, pkg/util/injection.go, pkg/util/status/build_status_test.go
I was messing around with Jetbrains GoLand and ran it's code inspection
against openshift/source-to-image and it found quite a few things, so
I went through and picked the ones that seemed like good ones to fix
and fixed them.
Some of the issues that were fixed consist of:
- Removing unused function parameters
- Removing unused non-exported function
- Replacing deprecated os.SEEK_SET with io.SeekStart
- Replacing deprecated msg.ProgressMessage with msg.Progress.Current
- Removing duplicate parenthesis
- Renaming variables that could mask imports
-  Renaming variable that used reserved word (new)
- Downcasing the first letter of error messages
I think that is mostly it, I am sure there will need to be some updates
to openshift/origin in response to these updates.
=> Miscellaneous cleanup and refactoring

pkg/build/strategies/sti/sti.go
It looks like /tmp/.s2i/image_metadata.json was never meant to be created during the assemble-runtime step, only during the assemble step, so tar was nil in that specific commitImageStep
Fixes #838
=> Fixes tar is nil on postExecutorSecondStageSteps.commitImageStep

hack/common.sh
fixes #851
just straight up removing it, i doubt anyone is running go 1.3 or earlier at this point anyway.
=> remove golang version check

pkg/tar/tar_test.go
Unclear why this is occurring, but this unit test failure was consistent on macOS.
=> Fixing tar unit test on macOS

pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/util/injection.go, pkg/util/injection_test.go, test/integration/integration_test.go
Adding a `Keep` option to `VolumeSpec` so that files can be kept in s2i builds.
This will be used to support the injection of `ConfigMap` build sources, which should not be truncated.
Trello card: https://trello.com/c/RMKJxJUm/1020-5-allow-using-a-configmap-as-an-input-to-a-build-builds
=> Keep Option for Injected Files

hack/build-test-images.sh, hack/test-integration.sh, pkg/api/describe/describer.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/cmd/cli/cmd/rebuild.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/errors/errors.go, test/integration/images/sti-fake-assemble-root/Dockerfile, test/integration/images/sti-fake-assemble-user/Dockerfile, test/integration/integration_test.go
Adding check to ensure the s2i assemble user is allowed if the `--allowed-uids` flag is set.
The assemble user can come from one of two sources:
1. `--assemble-user` flag
2. Builder image `io.openshift.s2i.assemble-user` label.
The assemble user overrides the default image user for an s2i build.
However, if the base image has ONBUILD instructions with USER directives,
all USER directives will be checked to ensure compliance.
Bug [1582976](https://bugzilla.redhat.com/show_bug.cgi?id=1582976)
=> Check Assemble Users Against Allowed UIDs

hack/build-test-images.sh, hack/test-integration.sh, pkg/api/describe/describer.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/cmd/cli/cmd/rebuild.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/errors/errors.go, test/integration/images/sti-fake-assemble-root/Dockerfile, test/integration/images/sti-fake-assemble-user/Dockerfile, test/integration/integration_test.go
Adding check to ensure the s2i assemble user is allowed if the --allowed-uids flag is set.
The assemble user can come from one of two sources:
1. --assemble-user flag
2. Builder image io.openshift.s2i.assemble-user label.
The assemble user overrides the default image user for an s2i build.
However, if the base image has ONBUILD instructions with USER directives,
all USER directives will be checked to ensure compliance.
Bug 1582976
Backport of #879 so we don't release the `as-dockerfile` feature to origin 3.10.
=> [3.10] Check Assemble Users Against Allowed UIDs

hack/build-test-images.sh, hack/test-integration.sh, hack/test-stirunimage.sh, pkg/api/describe/describer.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/cmd/cli/cmd/rebuild.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/errors/errors.go, test/integration/images/sti-fake-assemble-root/Dockerfile, test/integration/images/sti-fake-assemble-user/Dockerfile, test/integration/integration_test.go
Adding check to ensure the s2i assemble user is allowed if the --allowed-uids flag is set.
The assemble user can come from one of two sources:
1. --assemble-user flag
2. Builder image io.openshift.s2i.assemble-user label.
The assemble user overrides the default image user for an s2i build.
However, if the base image has ONBUILD instructions with USER directives,
all USER directives will be checked to ensure compliance.
Bug 1582976
Backport of #879 to origin 3.9
/assign @csrwng 
/cc @bparees @gabemontero
=> [3.9] Check Assemble Users Against Allowed UIDs

hack/build-test-images.sh, hack/test-integration.sh, hack/test-stirunimage.sh, pkg/api/describe/describer.go, pkg/build/strategies/sti/sti.go, pkg/build/strategies/strategies.go, pkg/cmd/cli/cmd/rebuild.go, pkg/docker/util.go, pkg/docker/util_test.go, pkg/errors/errors.go, test/integration/images/sti-fake-assemble-root/Dockerfile, test/integration/images/sti-fake-assemble-user/Dockerfile, test/integration/integration_test.go
Adding check to ensure the s2i assemble user is allowed if the --allowed-uids flag is set.
The assemble user can come from one of two sources:
1. --assemble-user flag
2. Builder image io.openshift.s2i.assemble-user label.
The assemble user overrides the default image user for an s2i build.
However, if the base image has ONBUILD instructions with USER directives,
all USER directives will be checked to ensure compliance.
Bug [1583421](https://bugzilla.redhat.com/show_bug.cgi?id=1583421)
Backport of #879 to origin 3.7
/assign @csrwng 
/cc @bparees @gabemontero
=> [3.7] Check Assemble Users Against Allowed UIDs

docs/cli.md
Add missing flags to our Github doc, as they are presented in the CLI.
Note that deprecated flags are ignored.
=> Update build flags in cli doc

examples/nginx-centos7/test/run, pkg/create/templates/test.go
This pull request contains some adjustments to the test/run script that is created when a new source-2-image project is bootstrapped using ```s2i create``` to make it work on both Linux and OSX. The nginx-centos7 example has been adjusted with the same changes. Additionally, it removes the "file://" uri which breaks the test as well.
=> Improve cross-platform compatibility in generated test script

pkg/build/strategies/sti/sti.go, pkg/util/injection.go, pkg/util/injection_test.go, test/integration/integration_test.go
- Added a "response file" to report failed injections on s2i
container
- Fixed assemble command to ensure s2i container exits if
injection fails
OpenShift bug [1608714](https://bugzilla.redhat.com/show_bug.cgi?id=1608714)
=> Fix Hang if Injected Dir Does Not Exist

README.md, hack/test-stirunimage.sh
github.com/openshift/django-ex has been moved to github.com/sclorg/django-ex
github.com/openshift/cakephp-ex has been moved to github.com/sclorg/cakephp-ex
=> Update example repos that were moved to sclorg

pkg/cmd/cli/cmd/build.go
afaict there is no need to have docker accessible for using `s2i build --as-dockerfile`
=> build: only check if docker is reachable when not using --as-dockerfile

contrib/completions/bash/s2i, contrib/completions/zsh/s2i, hack/test-stirunimage.sh, pkg/api/types.go, pkg/build/strategies/sti/sti.go, pkg/cmd/cli/cmd/build.go, pkg/docker/docker.go
Add a `--add-host` flag，same as `--add-host` in `docker run` . It is very useful when user in LAN or in dev environment.
=> add add-hosts

pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/dockerfile/dockerfile_test.go, test/integration/integration_test.go
* Raise an error if no scripts are downloaded from the ScriptsURL
* Update unit and integration tests to check for raised errors
Fixes [bug 1668130](https://bugzilla.redhat.com/show_bug.cgi?id=1668130)
=> dockerfile - Report Error if No Scripts Install

pkg/docker/docker.go, pkg/docker/docker_test.go
=> add seed to container name

cmd/s2i/s2i.go, pkg/cmd/cli/cli.go
Signed-off-by: soulseen <sunzhu@yunify.com>
=> remove basename in main(), the var basename is not used in func CommandFor()

pkg/create/templates/scripts.go
Hi,
When testing the code in the example 'assemble' script, the syntax didn't seem to work:
```
mv /tmp/artifacts/. ./
```
resulted in the error
```
mv: cannot move '/tmp/artifacts/.' to './.': Device or resource busy
```
Actually, I would have expected it to be:
```
mv /tmp/artifacts/* ./
```
Any thoughts on this?  Could you reproduce the error? 
A more thorough modification would be the following. This catches hidden files also.   
```
shopt -s dotglob
mv /tmp/artifacts/* ./
shopt -u dotglob
```
=> update restore-artifacts script

Dockerfile
This PR makes sure the `make` command runs as root user.
By default the USER in OSBS is changed to USER 1001, which makes build to fail.
=> Added build time user to get the build running in OSBS

pkg/cmd/cli/cmd/generate.go
URL-like image names are required by containers/image in order to find the right
image repository and were propagated to the resulting Dockerfile. This change fixes
that by using containers/image API to properly extract the proper Docker image name.
fixes #1017
=> Do not propagate URL-like image names to Dockerfile

docs/cli.md, hack/test-docker.sh, hack/test-dockerfile.sh, hack/test-go.sh, hack/verify-govet.sh, pkg/cmd/cli/cmd/generate.go, test/generate_test.go
=> Update documentation for generate and --as-dockerfile

docs/new_labels.md
A new section is added to new_labels.md on a bug in OpenShift 4.x. The method of updating output image labels during the s2i build process is not possible currently in OpenShift 4.x and a corresponding workaround is described.
=> Update of new_labels.md on a bug and corresponding workaround in OpenShift 4.x

pkg/docker/util.go, pkg/docker/util_test.go
Add option to set TLS in default docker config from environment variable DOCKER_TLS, same as docker cli (https://github.com/docker/cli/pull/863)
=> Add option to set TLS from environment variable

pkg/scm/git/url.go, pkg/scm/git/url_test.go
=> Bug 1884270: bypass golang url parsing with scp styled ssh git URLs; refactor URL for older git clients

.gitignore, hack/build-release.sh, images/release/Dockerfile
- Use bind mount instead of tar stream to add source code to the release
container.
- Update release Dockerfile to declare volume for the s2i source.
Command updated to remove tar stream in
- Add sti-version-defs file to .gitignore
=> Use volume mount in release build

pkg/scm/git/url.go, pkg/scm/git/url_test.go
we were just wrong with https://github.com/openshift/source-to-image/pull/1054
/assign @adambkaplan
=> Bug 1971332: revert incorrect allowance of ssh:// prefix with scp styled URLs

pkg/docker/util.go
When checking if the user that we'll use for running the assemble step is in the allowed user range, we strip any potential group part from the value for the user that we extract from the image's configuration before checking if it's in the allowed range, but we haven't been doing that for values configured through the "s2i.assemble-user" label.
=> Strip groups before checking if AssembleUser is Allowed

hack/common.sh
Fixes https://github.com/openshift/source-to-image/issues/1077.
@adambkaplan ptal.
=> Add {linux,darwin}/aarch64 to cross-compile platforms.

README.md
Update instructions to use `go install` instead of `go get` to have Go do all of the work of installing the current version of the code.
Note that `@latest` points `go install` at the latest tagged release, so until we tag something later than 1.3.1, we'll actually have to use `@master`, which is probably not recommended for the general case.
=> BUILD-486: update installation instructions to use `go install`

pkg/scm/git/testhelpers.go
The problem and suggested workaround are "documented" at https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html
This is needed to fix s2i in koschei (iow prevent FTBFS in future builds): https://koschei.fedoraproject.org/package/source-to-image
=> Fix tests after git CVE-2022-39253 fix

hack/common.sh
When running `go tool dist list` aarch64 is no longer listed so we must change it to arm64 which is the same architecture just a different name
Fixes #1103
=> Re-enable cross builds for aarch64/arm64

pkg/util/fs/fs.go
We can simplify the following code
```go
dir, err := os.Open(dirname)
if err != nil {
return err
}
defer dir.Close()
dirs, err := dir.Readdir(-1)
```
with just `os.ReadDir(dirname)`
Reference: https://pkg.go.dev/os#ReadDir
=> refactor(fs): simplify CopyContents

hack/common.sh, pkg/ignore/ignore_test.go, pkg/util/timeout.go
The `make release` command will now generate a `SHA512-SUMS.txt` file that should be uploaded to github when a release is made.
Also fixed an issue with the arm64 windows release not having a zip extension.
=> Generate SHA512SUM for release archives

.ci-operator.yaml, Dockerfile, OWNERS, go.mod, hack/build-release.sh
- Add .ci-operator.yaml file 
- Update OWNERS file
- Update to use Go 1.19
- Add fix for darwin (macos) in release script
=> A few small fixes

pkg/build/strategies/dockerfile/dockerfile.go, pkg/build/strategies/dockerfile/dockerfile_test.go
Whether the base image provides the scripts or not, the repository can supply override scripts. Removes the expectation/need of a location specified in the image.
=> Resolves #1124: Always scan the repository for provided scripts

.ci-operator.yaml, Dockerfile, Makefile, hack/build-release.sh, images/release/Dockerfile
- Update Dockerfiles to use the ubi9 go-toolset images. For the releaser image, this avoids downloading the go sdk as part of the relase process.
- Add `build-container` make target for convenience.
- Update ci-operator build root to use rhel-9 golang 1.20 image for OCP 4.15
=> BUILD-960: Update Containers to UBI9 go-toolset

.tekton/source-to-image-pull-request.yaml, .tekton/source-to-image-push.yaml
In preparation of the buidah 0.2 task, remove references to `BASE_IMAGES_DIGESTS`. This will be removed as an emitted result. Existing tasks that previously depend on this result no longer require this value.
=> chore: Konflux Migration for Buildah 0.2

.gitignore, Dockerfile
Changes:
- Use UIB8 based base imgae
- Use go-toolset from UBI8
Currently comet repo exists for rhel-8 based images, so to onboard to konflux easily we'll go ahead with rehl-8 image now. When comet repo for rhel-9 is configured, we'll switch to rehl-9 based images.
=> Use UBI8 based base image and builder image

.tekton/source-to-image-pull-request.yaml, .tekton/source-to-image-push.yaml, Dockerfile
Changes:
- Required labels added
- Hermetic build enabled
- Source image build enabled
=> Fix enterprise contract violations

Dockerfile
Changes:
- Update version from 1.4.0 to 1.4.1 in Dockerfile environment variables and labels
=> Update version from 1.4.0 to 1.4.1

Dockerfile
Use Red Hat's immutable tags to ensure reproducible builds. This will also teach Renovate to only apply z-stream updates for ubi8/go-toolset, and y-stream updates for ubi8/ubi-minimal.
=> NO-JIRA: Update Dockerfile with Immutable Tags

Dockerfile
Mirror of https://github.com/openshift/source-to-image/pull/1191
Updating the Dockerfile to require golang 1.22. Golang version was already updated to 1.22.5
Dockerfile has also been updated to use the "patch" version of the UBI base images. This ensures we have reproducible builds, since the "patch" tags from Red Hat are effectively immutable. Konflux should also provide updates to the patch version through Renovate.
=> BUILD-1165: Updating Dockerfile to us golang 1.22 image

.ci-operator.yaml, .tekton/source-to-image-pull-request.yaml, .tekton/source-to-image-push.yaml, Dockerfile, go.mod
Changes:
- Update Go to 1.22
- Update Dockerfile for FIPS compliance
- Disable btrfs to prevent build error due to missing library btrfs/ioct.h
=> BUILD-1190: Add FIPS compliance

Makefile
Update the `verify` Makefile target to build cross-compiled binaries. This ensures the s2i CLI can be released across all supported platforms at all times. Prevents future regressions of #1204.
=> fix: Verify Builds Cross-Compiled Binaries

.ci-operator.yaml, .tekton/source-to-image-rhel8-pull-request.yaml, .tekton/source-to-image-rhel9-push.yaml, Makefile, go.mod, hack/common.sh, images/release/Dockerfile, rhel8.Dockerfile, rhel9.Dockerfile
Changes:
- Update go.mod to 1.23
- Update Dockerfiles and CI
=> BUILD-1441: Update golang to 1.23

rhel8.Dockerfile, rhel9.Dockerfile
- using minor version tags for dockerfile ensures that the images
are built using latest update
Signed-off-by: Avinal Kumar <avinal@redhat.com>
=> chore: use minor version tags for docker images
